<?php

namespace App\Http\Controllers;

use Illuminate\View\View;

class DocsController extends Controller
{
    public function index(): View
    {
        return view('docs.index', [
            'sections' => $this->sections(),
            'appName'  => config('app.name', config('app.name')),
        ]);
    }

    public function show(string $slug): View
    {
        $sections = $this->sections();

        $section = collect($sections)->firstWhere('slug', $slug);
        abort_unless($section, 404);

        $appName = config('app.name', config('app.name'));

        $jsonLd = json_encode([
            '@context'   => 'https://schema.org',
            '@type'      => 'TechArticle',
            'headline'   => $section['title'],
            'description' => $section['lead'],
            'inLanguage' => 'id-ID',
            'isPartOf'   => [
                '@type' => 'CreativeWork',
                'name'  => 'Tutorial ' . $appName,
                'url'   => route('docs.index'),
            ],
        ], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

        return view('docs.show', [
            'sections' => $sections,
            'section'  => $section,
            'appName'  => $appName,
            'jsonLd'   => $jsonLd,
        ]);
    }

    /**
     * Materi tutorial — disusun sebagai:
     * 1) Pengantar → 2) Alur Bisnis end-to-end (13 langkah) → 3) Panduan per-menu
     * (15 navigation group) → 4) FAQ.
     */
    private function sections(): array
    {
        return [
            [
                'slug'  => 'pengantar',
                'icon'  => 'fa-book-open',
                'title' => 'Pengantar Aplikasi',
                'lead'  => 'Sekilas tentang Aplikasi Bengkel Terbaik, 15 navigation group, dan alur 13-status workflow.',
                'body'  => [
                    ['type' => 'p', 'text' => 'Aplikasi Bengkel Terbaik adalah aplikasi manajemen bengkel berbasis web dengan 60+ modul terintegrasi. Cakupannya menutup seluruh siklus harian: mulai dari booking online, check-in, inspeksi, approval customer, pengerjaan teknisi, QC, invoicing, pembayaran, sampai serah terima — plus akuntansi otomatis via AutoJournalService.'],
                    ['type' => 'p', 'text' => 'Tutorial ini menjelaskan urut-urutan pemakaian aplikasi seperti operator bekerja di hari pertama: baca <b>Alur Bisnis</b> dulu supaya paham aliran kerjanya, lalu ikuti panduan per-menu untuk detail tiap fitur.'],
                    ['type' => 'h', 'text' => '15 Navigation Group (Sidebar)'],
                    ['type' => 'ul', 'items' => [
                        '<b>📊 Dashboard</b> — ringkasan bisnis, chart, quick actions, notification bell',
                        '<b>🏭 Operations</b> — Booking Online, Cabang, Perusahaan, Customer, Kendaraan, Gate Passes',
                        '<b>🔧 Service Management</b> — Service, Jobcard, Service Package, Subkontraktor, Service History',
                        '<b>📦 Inventory</b> — Produk, Stok, Gudang, Supplier, Purchase, Purchase Requisition, Peralatan, Stock Adjustment, Stock Opname',
                        '<b>🛒 Sales & POS</b> — POS Kasir terminal, Sesi POS, Invoice, Retur Penjualan',
                        '<b>👨‍🔧 Technicians</b> — Teknisi, Komisi, Skill Matrix, Cuti',
                        '<b>📢 CRM & Marketing</b> — Voucher, Loyalty, Review, Blog, Campaign, Recall CRM',
                        '<b>🛡️ Warranty</b> — Garansi, Klaim Garansi, Recall, Klaim Asuransi, Klaim Supplier',
                        '<b>💰 Finance & Accounting</b> — COA, Journal, General Ledger, P&L, Balance Sheet, Kas Kecil, Income/Expense, Bank, Rekonsiliasi, Budget',
                        '<b>📈 Reports</b> — 13 jenis laporan (Service, Sales, Stock, Financial, Technician, Customer LTV, AR Aging, Parts Usage, Branch Comparison, Cash Flow, GL, P&L, Balance Sheet)',
                        '<b>🗂️ Master Data</b> — Vehicle, Product, Workshop, Finance (reference data)',
                        '<b>🌍 Geography</b> — Negara, Provinsi, Kota, Currency',
                        '<b>🔔 Notifications</b> — Template, Antrian, Log, Reminder Service',
                        '<b>👥 Users & Security</b> — User, Role, Permission, API Token, Activity Log',
                        '<b>⚙️ Settings</b> — General Settings, Invoice Layout, Payment Gateway, Backup & Restore',
                    ]],
                    ['type' => 'h', 'text' => 'Alur ringkas (end-to-end)'],
                    ['type' => 'ol', 'items' => [
                        'Setup awal: <b>Settings</b> profil bengkel, jam operasional, dan <b>Geography</b> (negara, provinsi, kota, currency).',
                        'Isi <b>Master Data</b> lengkap (jenis kendaraan, merk, BBM, warna, kategori produk, satuan, metode bayar, tarif pajak, kategori repair, observation types/points, service packages).',
                        'Daftarkan <b>Customer</b> dan <b>Kendaraan</b> di menu <b>Operations</b>. Customer Group (Fleet) untuk perusahaan dengan banyak kendaraan.',
                        'Buat <b>Booking Online</b> dari customer atau admin di menu <b>Operations → Booking Online</b>. Pilih tanggal & jam, assign teknisi.',
                        'Booking dikonversi ke <b>Service</b> di menu <b>Service Management</b> → otomatis menghasilkan <b>Jobcard</b> + QR Code.',
                        'Alur 13 status: <b>Booked → Checked In → Inspection → Waiting Approval → Approved → In Progress → Waiting Parts → QC → Ready → Invoiced → Paid → Released → Completed</b>.',
                        'Isi <b>Observation / Checklist</b>, tambahkan parts dari <b>Inventory</b> (auto-link stok & auto-berkurang), assign ke <b>Subkontraktor</b> jika perlu.',
                        'Kirim estimasi ke customer untuk <b>Approval via WhatsApp/Email</b> — customer bisa approve/reject.',
                        'Terbitkan <b>Invoice</b> dengan <b>Down Payment (DP)</b>, terima <b>Payment</b> (bisa cicil), kirim via WA/Email.',
                        '<b>Auto-Journal</b>: setiap invoice & payment otomatis generate journal entry (Piutang Usaha, Pendapatan, Kas, PPN) via <b>AutoJournalService</b>.',
                        'Buat <b>Gate Pass</b> dengan <b>Digital Signature</b> customer & teknisi di menu <b>Operations → Gate Passes</b>.',
                        'Tinjau <b>Reports</b>: 13 jenis laporan mencakup Service, Sales, Stock, Financial, Technician, Customer LTV, AR Aging, Cash Flow, dan laporan akuntansi.',
                        'Gunakan <b>POS Kasir</b> di menu <b>Sales & POS</b> untuk jual sparepart eceran walk-in.',
                        '<b>Next Service Auto-Reminder</b>: sistem otomatis deteksi kendaraan jatuh tempo service berdasarkan odo/tanggal.',
                    ]],
                    ['type' => 'screenshot', 'file' => 'dashboard.png', 'label' => 'Dashboard Utama', 'url' => '/admin', 'caption' => 'Tampilan dashboard setelah login — ringkasan service, revenue, stok rendah, chart, dan recent jobs.'],
                ],
            ],
            [
                'slug'  => 'alur-bisnis',
                'icon'  => 'fa-route',
                'title' => '1. Alur Bisnis Lengkap: Customer Datang → Bayar Lunas',
                'lead'  => 'Satu alur kerja end-to-end dari customer datang, booking, service, QC, invoice, pembayaran, sampai serah terima — lengkap dengan screenshot di setiap langkah.',
                'body'  => [
                    ['type' => 'p', 'text' => 'Ini adalah alur utama harian bengkel. Pahami urutannya dulu, karena semua menu lain (Inventory, Finance, Reports) sebenarnya menopang alur ini. Tabel di bawah merangkum 13 langkah dari customer datang sampai kendaraan keluar.'],
                    ['type' => 'table', 'rows' => [
                        ['1', 'Customer datang / Booking', 'Customer datang langsung atau booking online lebih dulu. Catat di Booking Online atau langsung buka Service baru.'],
                        ['2', 'Check-in kendaraan', 'Kendaraan masuk bengkel, kunci diserahkan, odometer dicatat, teknisi ditugaskan. Status: Checked In.'],
                        ['3', 'Inspeksi & checklist', 'Teknisi inspeksi menyeluruh: isi observation points, checklist, foto kerusakan. Status: Inspection.'],
                        ['4', 'Job Card + estimasi', 'Buat jobcard, susun estimasi biaya & pekerjaan. Status: Waiting Approval.'],
                        ['5', 'Approval customer via WA', 'Estimasi dikirim ke customer via WhatsApp/Email. Customer approve atau reject.'],
                        ['6', 'Teknisi kerja + pakai parts', 'Teknisi mengerjakan, memakai sparepart dari inventory (stok auto-berkurang). Status: In Progress.'],
                        ['7', 'Quality Control / QC', 'Pemeriksaan akhir: test drive, cek ulang semua point. Status: QC.'],
                        ['8', 'Ready for pickup', 'Kendaraan siap diambil. Sistem kirim notifikasi ke customer. Status: Ready.'],
                        ['9', 'Invoice dibuat', 'Terbitkan invoice lengkap dengan parts + jasa. Status: Invoiced.'],
                        ['10', 'Pembayaran', 'Terima pembayaran (bisa DP, cicil, atau lunas) via kasir/pos. Status: Paid.'],
                        ['11', 'Bayar Lunas', 'Pastikan invoice full paid, tidak ada sisa tagihan.'],
                        ['12', 'Gate Pass keluar', 'Buat gate pass + digital signature customer & teknisi. Status: Released.'],
                        ['13', 'Next service reminder', 'Sistem jadwalkan reminder service berikutnya otomatis. Status: Completed.'],
                    ]],
                    ['type' => 'h', 'text' => 'Langkah 1-2: Customer datang & check-in'],
                    ['type' => 'ol', 'items' => [
                        'Customer bisa <b>booking online</b> lebih dulu (via Customer Portal atau diinput admin) — daftar booking dikelola di <b>Operations → Booking Online</b>.',
                        'Saat kendaraan tiba, buka <b>Service Management → Add Service</b>, pilih customer & kendaraan, isi keluhan, catat odometer masuk.',
                        'Klik <b>Advance</b> ke status <b>Checked In</b> — timer SLA mulai berjalan.',
                    ]],
                    ['type' => 'screenshot', 'file' => 'booking-list.png', 'label' => 'Booking Online', 'url' => '/admin/bookings', 'caption' => 'Daftar booking online — kelola jadwal customer, konversi ke service dengan satu klik.'],
                    ['type' => 'screenshot', 'file' => 'service-create.png', 'label' => 'Form Service / Check-in', 'url' => '/admin/services/create', 'caption' => 'Form create service (check-in): pilih customer, kendaraan, service package, assign teknisi, catat odometer & keluhan.'],
                    ['type' => 'h', 'text' => 'Langkah 3-4: Inspeksi, jobcard & estimasi'],
                    ['type' => 'ol', 'items' => [
                        'Teknisi isi <b>observation points</b> & checklist inspeksi, upload foto kerusakan. Status pindah ke <b>Inspection</b>.',
                        'Jobcard otomatis terbuat — lengkap dengan QR Code untuk tracking. Buka di <b>Service Management → Jobcards</b>.',
                        'Susun estimasi: pilih sparepart dari inventory (Product Picker), tambah jasa, hitung total.',
                    ]],
                    ['type' => 'screenshot', 'file' => 'service-list.png', 'label' => 'Daftar Service / Inspeksi', 'url' => '/admin/services', 'caption' => 'Daftar semua service — filter per status 13-step workflow, cabang, teknisi, dan tanggal.'],
                    ['type' => 'screenshot', 'file' => 'jobcard-list.png', 'label' => 'Job Card + Estimasi', 'url' => '/admin/jobcards', 'caption' => 'Daftar job card — print dengan QR code, assign teknisi, isi odometer, estimasi biaya & rekomendasi service berikutnya.'],
                    ['type' => 'h', 'text' => 'Langkah 5: Approval customer via WhatsApp'],
                    ['type' => 'p', 'text' => 'Saat estimasi siap, status masuk <b>Waiting Approval</b>. Sistem otomatis kirim estimasi ke customer via WhatsApp/Email dengan link approve/reject. Customer bisa menyetujui langsung dari HP tanpa datang ke bengkel. Jika approved → status <b>Approved</b>; jika reject → kembali ke inspeksi untuk revisi estimasi.'],
                    ['type' => 'h', 'text' => 'Langkah 6-7: Teknisi kerja & QC'],
                    ['type' => 'ol', 'items' => [
                        'Teknisi mengerjakan service — status <b>In Progress</b>. Sparepart yang dipakai otomatis mengurangi stok di <b>Inventory</b>.',
                        'Jika menunggu sparepart, status pindah ke <b>Waiting Parts</b> (tidak dihitung ke SLA).',
                        'Setelah selesai, teknisi isi <b>checklist QC</b>: test drive, cek ulang semua point. Status <b>QC</b> → <b>Ready</b>.',
                    ]],
                    ['type' => 'screenshot', 'file' => 'product-list.png', 'label' => 'Product Picker (pakai parts)', 'url' => '/admin/products', 'caption' => 'Sparepart dari inventory — teknisi memakai parts, stok otomatis berkurang dan tercatat di stock history.'],
                    ['type' => 'screenshot', 'file' => 'service-history.png', 'label' => 'Service History / Ready', 'url' => '/admin/services/history', 'caption' => 'Riwayat service kendaraan — semua pekerjaan, parts terpakai, teknisi, dan biaya total tercatat rapi.'],
                    ['type' => 'h', 'text' => 'Langkah 8-11: Invoice, pembayaran & lunas'],
                    ['type' => 'ol', 'items' => [
                        'Terbitkan <b>Invoice</b> dari service — otomatis memuat parts + jasa. Bisa minta <b>Down Payment (DP)</b>.',
                        'Terima pembayaran via <b>Payment</b> (kas/transfer/QRIS) atau langsung di <b>POS Terminal</b> untuk sparepart eceran.',
                        'Saat lunas, status invoice <b>full_paid</b> dan service status <b>Paid</b>. AutoJournalService mencatat jurnal otomatis.',
                    ]],
                    ['type' => 'screenshot', 'file' => 'invoice-list.png', 'label' => 'Invoice List', 'url' => '/admin/invoices', 'caption' => 'Daftar invoice — 3 tipe (service/sales/parts), status pembayaran (dp_paid/full_paid), download PDF, kirim via WA/Email.'],
                    ['type' => 'screenshot', 'file' => 'pos-terminal.png', 'label' => 'POS Terminal (Pembayaran)', 'url' => '/admin/pos', 'caption' => 'Terminal POS kasir — terima pembayaran, barcode scan, pilih payment method, checkout cepat.'],
                    ['type' => 'h', 'text' => 'Langkah 12-13: Gate pass & reminder'],
                    ['type' => 'ol', 'items' => [
                        'Buat <b>Gate Pass</b> dengan digital signature customer & teknisi di <b>Operations → Gate Passes</b>. Status <b>Released</b>.',
                        'Sistem otomatis menjadwalkan <b>Next Service Reminder</b> berdasarkan odometer/tanggal — kirim H-7, H-3, H-1 via WA/Email.',
                        'Status <b>Completed</b> menutup alur. Semua dokumen lengkap: jobcard, invoice, payment, gate pass.',
                    ]],
                    ['type' => 'screenshot', 'file' => 'gate-pass-list.png', 'label' => 'Gate Pass Keluar', 'url' => '/admin/gate-passes', 'caption' => 'Surat jalan keluar — digital signature customer & teknisi, print siap serah terima kendaraan.'],
                    ['type' => 'screenshot', 'file' => 'reminder-list.png', 'label' => 'Next Service Reminder', 'url' => '/admin/reminders', 'caption' => 'Reminder service otomatis — H-7, H-3, H-1 sebelum jatuh tempo, kirim via WA/Email ke customer.'],
                    ['type' => 'tip', 'text' => 'Alur 13 status ini wajib dilewati berurutan. Sistem memvalidasi kelengkapan data di setiap tahap sebelum bisa <b>Advance</b> — jadi tidak ada langkah yang terlewat.'],
                ],
            ],
            [
                'slug'  => 'menu-dashboard',
                'icon'  => 'fa-gauge-high',
                'title' => '2. Menu Dashboard',
                'lead'  => 'Ringkasan bisnis real-time: stat cards, chart, quick actions, dan notification bell.',
                'body'  => [
                    ['type' => 'p', 'text' => 'Dashboard adalah halaman pertama setelah login. Di sini semua angka penting bengkel terpantau dalam satu layar dan auto-refresh setiap 60 detik.'],
                    ['type' => 'ul', 'items' => [
                        '<b>Stat Cards</b>: Total Service Aktif, Service Selesai Hari Ini, Revenue Hari Ini, Revenue Bulanan, Outstanding Invoice, Stok Rendah.',
                        '<b>Revenue Chart</b>: bar chart pendapatan vs pengeluaran 30 hari terakhir.',
                        '<b>Status Pie Chart</b>: doughnut distribusi status service (Booked → Completed).',
                        '<b>Per-Role Widgets</b>: Owner melihat Profit Bulanan & Revenue Chart; Manager melihat Pending Approvals; Teknisi melihat Task Saya; Kasir melihat Ringkasan POS Hari Ini.',
                        '<b>⚡ Quick Actions</b>: tombol [+ Booking], [+ Job Card], [+ Invoice] untuk langsung buat entri baru.',
                        '<b>🔔 Notification Bell</b> di topbar — badge merah jumlah notifikasi belum dibaca, klik untuk dropdown.',
                        '<b>Dark Mode Toggle</b> & <b>PWA installable</b> (install ke homescreen HP).',
                    ]],
                    ['type' => 'screenshot', 'file' => 'dashboard.png', 'label' => 'Dashboard Utama', 'url' => '/admin', 'caption' => 'Dashboard ringkasan bisnis — stat cards, revenue chart, status pie, quick actions, dan notification bell.'],
                ],
            ],
            [
                'slug'  => 'menu-operations',
                'icon'  => 'fa-industry',
                'title' => '3. Menu Operations',
                'lead'  => 'Grup operasional inti: Branches, Companies, Bookings, Job Cards/Services, Gate Passes, Vehicles, Customers, Customer Groups.',
                'body'  => [
                    ['type' => 'p', 'text' => 'Grup <b>Operations</b> berisi semua entitas operasional harian bengkel. Ini menu yang paling sering dibuka front-desk dan teknisi.'],
                    ['type' => 'h', 'text' => 'Branches (Cabang)'],
                    ['type' => 'p', 'text' => 'Kelola multi-cabang: nama, alamat, telepon, jam operasional, hari libur. Switcher cabang di topbar memfilter seluruh data per cabang.'],
                    ['type' => 'h', 'text' => 'Companies (Perusahaan)'],
                    ['type' => 'p', 'text' => 'Data perusahaan/entitas hukum yang menaungi bengkel — dipakai untuk identitas dokumen, faktur pajak, dan kontrak fleet.'],
                    ['type' => 'h', 'text' => 'Bookings (Booking Online)'],
                    ['type' => 'p', 'text' => 'Kelola jadwal booking customer. Status: Pending → Confirmed → Converted / Cancelled. Bisa dikonversi ke Service satu klik.'],
                    ['type' => 'h', 'text' => 'Job Cards / Services'],
                    ['type' => 'p', 'text' => 'Pusat workflow 13 status. Setiap service menghasilkan jobcard + QR Code, assign teknisi, inspeksi, estimasi, sampai selesai.'],
                    ['type' => 'h', 'text' => 'Gate Passes'],
                    ['type' => 'p', 'text' => 'Surat jalan keluar kendaraan dengan digital signature customer & teknisi (support touch screen).'],
                    ['type' => 'h', 'text' => 'Vehicles & Customers'],
                    ['type' => 'p', 'text' => 'Daftar kendaraan (plat unik, KM chart, service history) dan customer (HP, email, alamat, NPWP). Customer Group (Fleet) untuk perusahaan dengan banyak kendaraan.'],
                    ['type' => 'h', 'text' => 'Fleet Contracts (Kontrak Fleet)'],
                    ['type' => 'p', 'text' => 'Kelola kontrak servis rutin untuk perusahaan/fleet: interval servis (hari & KM), daftar kendaraan terikat kontrak, dan deteksi kendaraan yang jatuh tempo servis.'],
                    ['type' => 'screenshot', 'file' => 'branch-list.png', 'label' => 'Branches', 'url' => '/admin/branches', 'caption' => 'Daftar cabang bengkel — multi-cabang, alamat, telepon, dan jam operasional per cabang.'],
                    ['type' => 'screenshot', 'file' => 'company-list.png', 'label' => 'Companies', 'url' => '/admin/companies', 'caption' => 'Daftar perusahaan — identitas hukum, NPWP, dan entitas yang menaungi bengkel.'],
                    ['type' => 'screenshot', 'file' => 'booking-list.png', 'label' => 'Booking Online', 'url' => '/admin/bookings', 'caption' => 'Daftar booking — jadwal customer, konversi ke service dengan satu klik.'],
                    ['type' => 'screenshot', 'file' => 'fleet-contract-list.png', 'label' => 'Fleet Contracts', 'url' => '/admin/fleet-contracts', 'caption' => 'Kontrak fleet — interval servis rutin, daftar kendaraan terikat kontrak, deteksi jatuh tempo.'],
                    ['type' => 'screenshot', 'file' => 'gate-pass-list.png', 'label' => 'Gate Passes', 'url' => '/admin/gate-passes', 'caption' => 'Surat jalan keluar — digital signature customer & teknisi, print siap serah terima.'],
                    ['type' => 'screenshot', 'file' => 'vehicle-list.png', 'label' => 'Vehicles', 'url' => '/admin/vehicles', 'caption' => 'Daftar kendaraan — plat nomor, merk, tipe, tahun, odometer, dan service history.'],
                    ['type' => 'screenshot', 'file' => 'customer-list.png', 'label' => 'Customers', 'url' => '/admin/customers', 'caption' => 'Daftar customer — filter, search, import CSV, link ke kendaraan & customer group.'],
                ],
            ],
            [
                'slug'  => 'menu-service',
                'icon'  => 'fa-screwdriver-wrench',
                'title' => '4. Menu Service Management',
                'lead'  => 'Pusat pengerjaan: Services, Job Cards, Service Packages, dan Subcontractors.',
                'body'  => [
                    ['type' => 'p', 'text' => 'Grup <b>Service Management</b> adalah jantung aplikasi — semua pekerjaan servis dikelola dari sini.'],
                    ['type' => 'h', 'text' => 'Services'],
                    ['type' => 'p', 'text' => 'Daftar semua service dengan filter 13 status, cabang, teknisi, dan tanggal. Halaman detail menampilkan observation/checklist, parts, estimasi, approval, dan tombol Advance ke status berikutnya.'],
                    ['type' => 'h', 'text' => 'Job Cards'],
                    ['type' => 'p', 'text' => 'Jobcard otomatis terbuat saat service dibuat. Isi odometer in/out, assign teknisi, print dengan QR Code. Ada deteksi konflik jadwal teknisi.'],
                    ['type' => 'h', 'text' => 'Service Packages'],
                    ['type' => 'p', 'text' => 'Template paket service (Tune-up, Ganti Oli, Rem) — sekali pilih, harga, estimasi jam, dan item invoice auto terisi.'],
                    ['type' => 'h', 'text' => 'Subcontractors'],
                    ['type' => 'p', 'text' => 'Tracking pekerjaan yang di-sub ke pihak ketiga (body repair, AC, kelistrikan): spesialisasi, biaya, status, dan history.'],
                    ['type' => 'screenshot', 'file' => 'service-list.png', 'label' => 'Services', 'url' => '/admin/services', 'caption' => 'Daftar service — filter per status 13-step, cabang, teknisi, tanggal.'],
                    ['type' => 'screenshot', 'file' => 'service-create.png', 'label' => 'Add Service', 'url' => '/admin/services/create', 'caption' => 'Form create service — pilih customer, kendaraan, service package, assign teknisi, estimasi biaya.'],
                    ['type' => 'screenshot', 'file' => 'jobcard-list.png', 'label' => 'Job Cards', 'url' => '/admin/jobcards', 'caption' => 'Daftar job card — print QR code, assign teknisi, odometer, rekomendasi service berikutnya.'],
                ],
            ],
            [
                'slug'  => 'menu-inventory',
                'icon'  => 'fa-boxes-stacked',
                'title' => '5. Menu Inventory',
                'lead'  => 'Produk, gudang, supplier, pembelian, requisition, peralatan, stock adjustment & opname.',
                'body'  => [
                    ['type' => 'p', 'text' => 'Grup <b>Inventory</b> mengelola sparepart dan peralatan bengkel. Terintegrasi dengan service & POS — stok otomatis berkurang saat parts dipakai atau terjual.'],
                    ['type' => 'h', 'text' => 'Products'],
                    ['type' => 'p', 'text' => 'Daftar sparepart: kode, barcode, harga beli/jual, stok per gudang, supplier terkait, reorder alert.'],
                    ['type' => 'h', 'text' => 'Warehouses (Gudang)'],
                    ['type' => 'p', 'text' => 'Multi-gudang per cabang, stok per rak, dan transfer stok antar gudang otomatis.'],
                    ['type' => 'h', 'text' => 'Suppliers'],
                    ['type' => 'p', 'text' => 'Daftar supplier sparepart — kontak, alamat, history pembelian, perbandingan harga antar supplier.'],
                    ['type' => 'h', 'text' => 'Purchases & Purchase Orders'],
                    ['type' => 'p', 'text' => 'Purchase order ke supplier → mark received → stok auto bertambah + history. Purchase returns untuk retur barang ke supplier.'],
                    ['type' => 'h', 'text' => 'Requisitions'],
                    ['type' => 'p', 'text' => 'Permintaan pengadaan sparepart internal — dari teknisi/service yang butuh parts sampai disetujui menjadi purchase order.'],
                    ['type' => 'h', 'text' => 'Equipment (Peralatan)'],
                    ['type' => 'p', 'text' => 'Daftar alat bengkel: lift, scanner, kompresor — status (tersedia/dipakai/maintenance/rusak) dan maintenance log.'],
                    ['type' => 'h', 'text' => 'Stock Adjustments & Stock Opname'],
                    ['type' => 'p', 'text' => 'Koreksi stok dengan workflow approval (opname/rusak/hilang/expired). Selisih otomatis dihitung, semua tercatat di stock history untuk audit.'],
                    ['type' => 'screenshot', 'file' => 'product-list.png', 'label' => 'Products', 'url' => '/admin/products', 'caption' => 'Daftar produk sparepart — kode, barcode, harga beli/jual, stok per gudang, supplier terkait.'],
                    ['type' => 'screenshot', 'file' => 'warehouse-list.png', 'label' => 'Warehouses', 'url' => '/admin/warehouses', 'caption' => 'Daftar gudang multi-cabang — stok per gudang, rak, transfer stok antar gudang.'],
                    ['type' => 'screenshot', 'file' => 'supplier-list.png', 'label' => 'Suppliers', 'url' => '/admin/suppliers', 'caption' => 'Daftar supplier — kontak, history pembelian, perbandingan harga.'],
                    ['type' => 'screenshot', 'file' => 'purchase-list.png', 'label' => 'Purchases', 'url' => '/admin/purchases', 'caption' => 'Daftar purchase order — status order, receiving, auto-update stok.'],
                    ['type' => 'screenshot', 'file' => 'purchase-return.png', 'label' => 'Purchase Returns', 'url' => '/admin/purchases/return', 'caption' => 'Retur pembelian — barang kembali ke supplier, stok berkurang, history tercatat.'],
                    ['type' => 'screenshot', 'file' => 'purchase-requisition-list.png', 'label' => 'Requisitions', 'url' => '/admin/purchase-requisitions', 'caption' => 'Permintaan pengadaan — dari internal sampai disetujui jadi purchase order.'],
                    ['type' => 'screenshot', 'file' => 'equipment-list.png', 'label' => 'Equipment', 'url' => '/admin/equipment', 'caption' => 'Daftar peralatan bengkel — lift, scanner, kompresor, status & maintenance log.'],
                    ['type' => 'screenshot', 'file' => 'stock-adjustments.png', 'label' => 'Stock Adjustments', 'url' => '/admin/stock-adjustments', 'caption' => 'Daftar stock adjustment — status pending/approved/rejected, tipe opname/rusak/hilang/expired.'],
                    ['type' => 'screenshot', 'file' => 'product-stock-opname.png', 'label' => 'Stock Opname', 'url' => '/admin/stock-opname', 'caption' => 'Stock opname — hitung fisik, sistem hitung selisih vs stok sistem, submit untuk approval.'],
                ],
            ],
            [
                'slug'  => 'menu-sales-pos',
                'icon'  => 'fa-cash-register',
                'title' => '6. Menu Sales & POS',
                'lead'  => 'POS Terminal, POS Sessions, Invoices, dan Sell Returns untuk penjualan sparepart eceran.',
                'body'  => [
                    ['type' => 'p', 'text' => 'Grup <b>Sales & POS</b> menangani penjualan kasir — baik invoice service maupun penjualan sparepart eceran walk-in.'],
                    ['type' => 'h', 'text' => 'POS Terminal'],
                    ['type' => 'p', 'text' => 'Terminal kasir dengan grid produk, barcode scan, pilih customer & payment method, checkout cepat. Stok berkurang otomatis + invoice + payment record + stock history ter-generate.'],
                    ['type' => 'h', 'text' => 'POS Sessions'],
                    ['type' => 'p', 'text' => 'Tracking shift kasir: buka/tutup sesi, saldo awal/akhir, selisih, riwayat transaksi per sesi.'],
                    ['type' => 'h', 'text' => 'Invoices'],
                    ['type' => 'p', 'text' => 'Invoice 3 tipe (service/sales/parts) dengan down payment (DP), pembayaran cicil, kirim via WA/Email, dan link pembayaran QRIS.'],
                    ['type' => 'h', 'text' => 'Sell Returns (Retur Penjualan)'],
                    ['type' => 'p', 'text' => 'Retur barang dari customer — stok kembali bertambah, refund tercatat, history lengkap.'],
                    ['type' => 'screenshot', 'file' => 'pos-terminal.png', 'label' => 'POS Terminal', 'url' => '/admin/pos', 'caption' => 'Terminal POS kasir — grid produk, barcode scan, checkout cepat.'],
                    ['type' => 'screenshot', 'file' => 'pos-sessions.png', 'label' => 'POS Sessions', 'url' => '/admin/pos/sessions', 'caption' => 'Sesi POS — tracking shift buka/tutup, saldo awal/akhir, selisih, riwayat transaksi.'],
                    ['type' => 'screenshot', 'file' => 'invoice-list.png', 'label' => 'Invoices', 'url' => '/admin/invoices', 'caption' => 'Daftar invoice — 3 tipe, status pembayaran, download PDF, kirim WA/Email.'],
                    ['type' => 'screenshot', 'file' => 'sell-return-list.png', 'label' => 'Sell Returns', 'url' => '/admin/sell-returns', 'caption' => 'Retur penjualan — barang kembali ke stok, refund tercatat, history lengkap.'],
                ],
            ],
            [
                'slug'  => 'menu-technicians',
                'icon'  => 'fa-user-gear',
                'title' => '7. Menu Technicians',
                'lead'  => 'Komisi teknisi, skill matrix, dan cuti/absensi dalam satu grup.',
                'body'  => [
                    ['type' => 'p', 'text' => 'Grup <b>Technicians</b> mengelola kinerja dan sumber daya teknisi — dari komisi sampai kompetensi.'],
                    ['type' => 'h', 'text' => 'Commissions (Komisi)'],
                    ['type' => 'p', 'text' => 'Hitung komisi teknisi otomatis per service, filter periode, mark paid batch, laporan per teknisi.'],
                    ['type' => 'h', 'text' => 'Skill Matrix'],
                    ['type' => 'p', 'text' => 'Peta kompetensi teknisi: skill yang dikuasai (mesin, kelistrikan, AC, body), level keahlian, dan sertifikasi — membantu assign teknisi yang tepat.'],
                    ['type' => 'h', 'text' => 'Leave (Cuti)'],
                    ['type' => 'p', 'text' => 'Pengajuan cuti & absensi teknisi — clock-in/out, approval manager, dan history cuti.'],
                    ['type' => 'screenshot', 'file' => 'commission-list.png', 'label' => 'Commissions', 'url' => '/admin/commissions', 'caption' => 'Komisi teknisi — filter periode, hitung otomatis per service, mark paid batch.'],
                    ['type' => 'screenshot', 'file' => 'technician-skills.png', 'label' => 'Skill Matrix', 'url' => '/admin/technician-skills', 'caption' => 'Skill matrix teknisi — peta kompetensi, level keahlian, sertifikasi untuk assign teknisi tepat.'],
                    ['type' => 'screenshot', 'file' => 'leave-list.png', 'label' => 'Leave & Attendance', 'url' => '/admin/leaves', 'caption' => 'Cuti & absensi teknisi — clock-in/out, pengajuan cuti, approval manager.'],
                ],
            ],
            [
                'slug'  => 'menu-crm',
                'icon'  => 'fa-bullhorn',
                'title' => '8. Menu CRM & Marketing',
                'lead'  => 'Vouchers, Loyalty, Reviews, Blog, dan Campaigns untuk menarik & menahan customer.',
                'body'  => [
                    ['type' => 'p', 'text' => 'Grup <b>CRM & Marketing</b> berisi tools untuk menarik customer baru dan mempertahankan customer lama.'],
                    ['type' => 'h', 'text' => 'Vouchers'],
                    ['type' => 'p', 'text' => 'Generate kode promo dengan diskon nominal/persen, minimal transaksi, masa berlaku, kuota pemakaian.'],
                    ['type' => 'h', 'text' => 'Loyalty & Membership'],
                    ['type' => 'p', 'text' => 'Poin per transaksi, tier Bronze→Silver→Gold→Platinum, leaderboard, dan reward redemption.'],
                    ['type' => 'h', 'text' => 'Reviews'],
                    ['type' => 'p', 'text' => 'Kumpulkan rating & review dari customer setelah service, publish/hide, admin reply.'],
                    ['type' => 'h', 'text' => 'Blog'],
                    ['type' => 'p', 'text' => 'CRUD artikel blog + RSS feed + auto sitemap. Artikel tampil di <code>/blog</code> publik untuk SEO.'],
                    ['type' => 'h', 'text' => 'Campaigns'],
                    ['type' => 'p', 'text' => 'Bulk WhatsApp/SMS blast ke daftar customer. Antrian di notification queue, diproses scheduler tiap 5 menit.'],
                    ['type' => 'screenshot', 'file' => 'voucher-list.png', 'label' => 'Vouchers', 'url' => '/admin/vouchers', 'caption' => 'Daftar voucher & promo — kode diskon, minimal transaksi, masa berlaku, kuota.'],
                    ['type' => 'screenshot', 'file' => 'loyalty-list.png', 'label' => 'Loyalty & Membership', 'url' => '/admin/loyalty', 'caption' => 'Loyalty — poin per transaksi, tier Bronze/Silver/Gold/Platinum, leaderboard, reward.'],
                    ['type' => 'screenshot', 'file' => 'review-list.png', 'label' => 'Reviews', 'url' => '/admin/reviews', 'caption' => 'Review customer — rating bintang, feedback, publish/hide, admin reply.'],
                ],
            ],
            [
                'slug'  => 'menu-warranty',
                'icon'  => 'fa-shield-halved',
                'title' => '9. Menu Warranty',
                'lead'  => 'Warranty Claims, Recalls, Insurance Claims, dan Supplier Claims.',
                'body'  => [
                    ['type' => 'p', 'text' => 'Grup <b>Warranty</b> menangani perlindungan aset: garansi sparepart, recall, dan klaim ke asuransi/supplier.'],
                    ['type' => 'h', 'text' => 'Warranty Claims (Garansi & Klaim Garansi)'],
                    ['type' => 'p', 'text' => 'Setup periode garansi per produk/kategori. Service dalam masa garansi auto-flag dan biaya parts Rp 0. Customer ajukan klaim → teknisi verifikasi → approve/reject → buat service gratis.'],
                    ['type' => 'h', 'text' => 'Recalls'],
                    ['type' => 'p', 'text' => 'Recall produk/unit bermasalah — lacak batch sparepart yang perlu ditarik, notify customer terdampak.'],
                    ['type' => 'h', 'text' => 'Insurance Claims (Klaim Asuransi)'],
                    ['type' => 'p', 'text' => 'Kelola klaim asuransi kendaraan customer — dokumen, status klaim, dan pelacakan pembayaran dari asuransi.'],
                    ['type' => 'h', 'text' => 'Supplier Claims (Klaim Supplier)'],
                    ['type' => 'p', 'text' => 'Klaim ke supplier untuk sparepart cacat/rusak — terkait langsung dengan purchase dan stok.'],
                    ['type' => 'screenshot', 'file' => 'warranty-list.png', 'label' => 'Warranty Claims', 'url' => '/admin/warranties', 'caption' => 'Garansi & klaim garansi — periode garansi per produk, auto-flag service, tracking klaim.'],
                    ['type' => 'screenshot', 'file' => 'recall-list.png', 'label' => 'Recalls', 'url' => '/admin/recalls', 'caption' => 'Recall — lacak produk/unit bermasalah, notify customer terdampak.'],
                    ['type' => 'screenshot', 'file' => 'insurance-list.png', 'label' => 'Insurance Claims', 'url' => '/admin/insurance-claims', 'caption' => 'Klaim asuransi — dokumen, status klaim, pelacakan pembayaran dari asuransi.'],
                    ['type' => 'screenshot', 'file' => 'supplier-claims-list.png', 'label' => 'Supplier Claims', 'url' => '/admin/supplier-claims', 'caption' => 'Klaim supplier — sparepart cacat/rusak, terkait purchase & stok.'],
                ],
            ],
            [
                'slug'  => 'menu-finance',
                'icon'  => 'fa-coins',
                'title' => '10. Menu Finance & Accounting',
                'lead'  => 'Income, Expenses, Petty Cash, Bank Accounts, Bank Reconciliation, Budget, COA, dan Journal.',
                'body'  => [
                    ['type' => 'p', 'text' => 'Grup <b>Finance & Accounting</b> adalah fondasi akuntansi. Didukung AutoJournalService — setiap transaksi operasional otomatis tercatat ke buku besar.'],
                    ['type' => 'h', 'text' => 'Income & Expenses'],
                    ['type' => 'p', 'text' => 'Catat pemasukan & pengeluaran non-operasional, kategori, dan link ke COA. Total amount badge ikut filter tanggal.'],
                    ['type' => 'h', 'text' => 'Petty Cash (Kas Kecil)'],
                    ['type' => 'p', 'text' => 'Catat transaksi kas kecil harian — kas masuk & keluar, saldo otomatis terhitung, link ke COA.'],
                    ['type' => 'h', 'text' => 'Bank Accounts'],
                    ['type' => 'p', 'text' => 'Daftar rekening bank bengkel — saldo, jenis rekening, dan link ke transaksi.'],
                    ['type' => 'h', 'text' => 'Bank Reconciliation (Rekonsiliasi Bank)'],
                    ['type' => 'p', 'text' => 'Cocokkan saldo bank sistem vs mutasi rekening riil, tandai transaksi yang clear/unclear, hitung selisih.'],
                    ['type' => 'h', 'text' => 'Budget (Anggaran)'],
                    ['type' => 'p', 'text' => 'Buat anggaran per kategori/periode, pantau realisasi vs anggaran, kontrol pengeluaran.'],
                    ['type' => 'h', 'text' => 'COA (Chart of Accounts)'],
                    ['type' => 'p', 'text' => 'Setup akun akuntansi: Aset, Liabilitas, Ekuitas, Pendapatan, Beban — kode unik per akun.'],
                    ['type' => 'h', 'text' => 'Journal Entry'],
                    ['type' => 'p', 'text' => 'Jurnal double-entry manual: debit = kredit, attach bukti, total otomatis. Auto-journal juga tercatat di sini.'],
                    ['type' => 'screenshot', 'file' => 'income-list.png', 'label' => 'Income', 'url' => '/admin/incomes', 'caption' => 'Pemasukan non-operasional — kategori, jumlah, tanggal, total amount badge.'],
                    ['type' => 'screenshot', 'file' => 'expense-list.png', 'label' => 'Expenses', 'url' => '/admin/expenses', 'caption' => 'Pengeluaran operasional — kuitansi, kategori, COA link, ringkasan total.'],
                    ['type' => 'screenshot', 'file' => 'petty-cash.png', 'label' => 'Petty Cash', 'url' => '/admin/petty-cash', 'caption' => 'Kas kecil harian — kas masuk/keluar, saldo otomatis, link COA.'],
                    ['type' => 'screenshot', 'file' => 'bank-account-list.png', 'label' => 'Bank Accounts', 'url' => '/admin/bank-accounts', 'caption' => 'Rekening bank — saldo, jenis rekening, link transaksi.'],
                    ['type' => 'screenshot', 'file' => 'bank-reconciliation-list.png', 'label' => 'Bank Reconciliation', 'url' => '/admin/bank-reconciliations', 'caption' => 'Rekonsiliasi bank — cocokkan saldo sistem vs mutasi riil, tandai clear/unclear.'],
                    ['type' => 'screenshot', 'file' => 'budget-list.png', 'label' => 'Budget', 'url' => '/admin/budgets', 'caption' => 'Anggaran — budget per kategori/periode, realisasi vs anggaran.'],
                    ['type' => 'screenshot', 'file' => 'coa-list.png', 'label' => 'Chart of Accounts', 'url' => '/admin/chart-of-accounts', 'caption' => 'Daftar COA — kode unik, tipe akun, saldo debit/kredit.'],
                    ['type' => 'screenshot', 'file' => 'journal-list.png', 'label' => 'Journal Entries', 'url' => '/admin/journal-entries', 'caption' => 'Jurnal double-entry — debit = kredit, attach bukti, filter per akun & tanggal.'],
                ],
            ],
            [
                'slug'  => 'menu-reports',
                'icon'  => 'fa-chart-column',
                'title' => '11. Menu Reports (13 Jenis Laporan)',
                'lead'  => '13 laporan siap saji: Service, Sales, Stock, Financial, Technician, Customer LTV, AR Aging, Parts Usage, Branch Comparison, Cash Flow, GL, P&L, Balance Sheet.',
                'body'  => [
                    ['type' => 'p', 'text' => 'Grup <b>Reports</b> menyajikan 13 jenis laporan interaktif dengan date filter, chart, dan export PDF/Excel.'],
                    ['type' => 'table', 'rows' => [
                        ['Service Report', 'Volume service per kategori & teknisi, filter tanggal & cabang.'],
                        ['Sales Report', 'Penjualan parts & jasa per periode, breakdown per produk/kategori.'],
                        ['Stock Report', 'Stok berjalan, slow-moving items, reorder alert, stock valuation.'],
                        ['Financial Report', 'Profit/Loss bulanan, income vs expense, cash flow summary.'],
                        ['Technician Performance', 'Produktivitas teknisi: job count, revenue, avg durasi pengerjaan.'],
                        ['Customer Lifetime Value', 'Top 20 customer: total spending, jumlah kunjungan, avg per visit.'],
                        ['AR Aging Report', 'Piutang usaha — breakdown overdue 30/60/90+ hari.'],
                        ['Parts Usage Report', 'Pemakaian sparepart — top moving items, usage per service.'],
                        ['Branch Comparison', 'Perbandingan cabang: revenue, service count, profit margin.'],
                        ['Cash Flow Report', 'Arus kas masuk vs keluar, net cash flow per bulan.'],
                        ['General Ledger', 'Buku besar — mutasi debit/kredit per akun, saldo awal & akhir.'],
                        ['Profit & Loss', 'Laba rugi — pendapatan dikurangi beban = laba/rugi bersih.'],
                        ['Balance Sheet', 'Neraca — Aset = Liabilitas + Ekuitas, untuk tutup buku.'],
                    ]],
                    ['type' => 'screenshot', 'file' => 'report-service.png', 'label' => 'Service Report', 'url' => '/admin/reports/service', 'caption' => 'Laporan service — volume per kategori & teknisi, chart batang, export PDF/Excel.'],
                    ['type' => 'screenshot', 'file' => 'report-sales.png', 'label' => 'Sales Report', 'url' => '/admin/reports/sales', 'caption' => 'Laporan penjualan — parts & jasa per periode, breakdown per produk/kategori.'],
                    ['type' => 'screenshot', 'file' => 'report-stock.png', 'label' => 'Stock Report', 'url' => '/admin/reports/stock', 'caption' => 'Laporan stok — stok berjalan, slow-moving, reorder alert, valuation.'],
                    ['type' => 'screenshot', 'file' => 'report-financial.png', 'label' => 'Financial Report', 'url' => '/admin/reports/financial', 'caption' => 'Laporan keuangan — Profit/Loss bulanan, income vs expense, cash flow summary.'],
                    ['type' => 'screenshot', 'file' => 'report-technician.png', 'label' => 'Technician Performance', 'url' => '/admin/reports/technician', 'caption' => 'Performa teknisi — job count, revenue, avg durasi, chart perbandingan.'],
                    ['type' => 'screenshot', 'file' => 'report-customer-lifetime.png', 'label' => 'Customer Lifetime Value', 'url' => '/admin/reports/customer-ltv', 'caption' => 'Customer LTV — top 20 customer, total spending, jumlah kunjungan.'],
                    ['type' => 'screenshot', 'file' => 'report-ar-aging.png', 'label' => 'AR Aging Report', 'url' => '/admin/reports/ar-aging', 'caption' => 'Piutang usaha — breakdown overdue 30/60/90+ hari, total outstanding.'],
                    ['type' => 'screenshot', 'file' => 'report-parts-usage.png', 'label' => 'Parts Usage Report', 'url' => '/admin/reports/parts-usage', 'caption' => 'Pemakaian sparepart — top moving items, usage per service, mutasi stok.'],
                    ['type' => 'screenshot', 'file' => 'report-branch-comparison.png', 'label' => 'Branch Comparison', 'url' => '/admin/reports/branch-comparison', 'caption' => 'Perbandingan cabang — revenue, service count, profit margin per cabang.'],
                    ['type' => 'screenshot', 'file' => 'report-cash-flow.png', 'label' => 'Cash Flow Report', 'url' => '/admin/reports/cash-flow', 'caption' => 'Arus kas — kas masuk vs keluar, net cash flow per bulan.'],
                    ['type' => 'screenshot', 'file' => 'report-general-ledger.png', 'label' => 'General Ledger', 'url' => '/admin/reports/general-ledger', 'caption' => 'Buku besar — mutasi debit/kredit per akun, saldo awal & akhir.'],
                    ['type' => 'screenshot', 'file' => 'report-profit-loss.png', 'label' => 'Profit & Loss', 'url' => '/admin/reports/profit-loss', 'caption' => 'Laba rugi — pendapatan dikurangi beban, bandingkan periode.'],
                    ['type' => 'screenshot', 'file' => 'report-balance-sheet.png', 'label' => 'Balance Sheet', 'url' => '/admin/reports/balance-sheet', 'caption' => 'Neraca — Aset = Liabilitas + Ekuitas, untuk tutup buku.'],
                ],
            ],
            [
                'slug'  => 'menu-master-data',
                'icon'  => 'fa-database',
                'title' => '12. Menu Master Data',
                'lead'  => 'Data referensi Vehicle, Product, Workshop, dan Finance — isi sekali, dipakai selamanya.',
                'body'  => [
                    ['type' => 'p', 'text' => 'Grup <b>Master Data</b> berisi data referensi yang dipakai berulang di seluruh aplikasi. Isi lengkap di awal supaya operasional lancar.'],
                    ['type' => 'h', 'text' => 'Vehicle (Kendaraan)'],
                    ['type' => 'p', 'text' => 'Vehicle Types (Mobil/Motor/Truk/Bus), Brands (Toyota/Honda/Yamaha/Suzuki/Hino), Fuel Types, Colors.'],
                    ['type' => 'h', 'text' => 'Product (Sparepart)'],
                    ['type' => 'p', 'text' => 'Product Types (Oli/Filter/Rem/Aki/CVT), Product Units (Pcs/Liter/Set/Pasang/Botol).'],
                    ['type' => 'h', 'text' => 'Workshop (Operasional)'],
                    ['type' => 'p', 'text' => 'Repair Categories, Observation Types & Points, Inspection Points, Checkout Categories, Service Packages.'],
                    ['type' => 'h', 'text' => 'Finance'],
                    ['type' => 'p', 'text' => 'Payment Methods (Cash/Transfer/QRIS/GoPay/OVO/Dana), Tax Rates (PPN 11%/0%).'],
                    ['type' => 'screenshot', 'file' => 'settings.png', 'label' => 'Master Data & Referensi', 'url' => '/admin/master-data', 'caption' => 'Data referensi — jenis kendaraan, merk, kategori produk, satuan, metode bayar, tarif pajak, dan paket service.'],
                ],
            ],
            [
                'slug'  => 'menu-geography',
                'icon'  => 'fa-earth-asia',
                'title' => '13. Menu Geography',
                'lead'  => 'Negara, provinsi, kota, dan mata uang — dipakai alamat & multi-cabang.',
                'body'  => [
                    ['type' => 'p', 'text' => 'Grup <b>Geography</b> menyimpan data wilayah untuk alamat customer, supplier, dan cabang.'],
                    ['type' => 'ul', 'items' => [
                        '<b>Countries (Negara)</b> — daftar negara (Indonesia sudah ter-seed).',
                        '<b>Provinces (Provinsi)</b> — provinsi per negara, dipakai di alamat.',
                        '<b>Cities (Kota)</b> — kota per provinsi.',
                        '<b>Currencies (Mata Uang)</b> — default IDR, bisa tambah untuk transaksi lintas negara.',
                    ]],
                    ['type' => 'screenshot', 'file' => 'settings.png', 'label' => 'Geography Setup', 'url' => '/admin/geography', 'caption' => 'Data wilayah — negara, provinsi, kota, dan mata uang untuk alamat & multi-cabang.'],
                ],
            ],
            [
                'slug'  => 'menu-notifications',
                'icon'  => 'fa-bell',
                'title' => '14. Menu Notifications',
                'lead'  => 'Templates, Reminders, dan Logs — semua notifikasi WA/Email/SMS terkelola di sini.',
                'body'  => [
                    ['type' => 'p', 'text' => 'Grup <b>Notifications</b> mengelola semua notifikasi multi-channel (WhatsApp, Email, SMS).'],
                    ['type' => 'h', 'text' => 'Templates'],
                    ['type' => 'p', 'text' => 'Template WA/Email/SMS dengan variabel <code>{customer_name}</code>, <code>{plate}</code>, <code>{next_service_date}</code>.'],
                    ['type' => 'h', 'text' => 'Reminders'],
                    ['type' => 'p', 'text' => 'Next Service Auto-Reminder — deteksi kendaraan jatuh tempo service (odo/tanggal), kirim H-7, H-3, H-1 via WA/Email.'],
                    ['type' => 'h', 'text' => 'Logs'],
                    ['type' => 'p', 'text' => 'Log semua notifikasi terkirim beserta timestamp & status (pending/sent/failed). Queue diproses scheduler tiap 5 menit.'],
                    ['type' => 'screenshot', 'file' => 'notification-templates.png', 'label' => 'Notification Templates', 'url' => '/admin/notification-templates', 'caption' => 'Template notifikasi — buat template WA/Email/SMS dengan variabel.'],
                    ['type' => 'screenshot', 'file' => 'reminder-list.png', 'label' => 'Service Reminders', 'url' => '/admin/reminders', 'caption' => 'Reminder service otomatis — H-7, H-3, H-1 sebelum jatuh tempo.'],
                ],
            ],
            [
                'slug'  => 'menu-users',
                'icon'  => 'fa-user-shield',
                'title' => '15. Menu Users & Security',
                'lead'  => 'Users, Roles, Activity Log, dan API Tokens — kendali akses penuh.',
                'body'  => [
                    ['type' => 'p', 'text' => 'Grup <b>Users & Security</b> mengelola siapa yang boleh mengakses apa, plus jejak audit.'],
                    ['type' => 'h', 'text' => 'Users'],
                    ['type' => 'p', 'text' => 'CRUD user, assign cabang & role, aktif/nonaktif, reset password.'],
                    ['type' => 'h', 'text' => 'Roles & Permissions'],
                    ['type' => 'p', 'text' => 'Permission granular per modul. 5 role preset: super_admin, admin, manager, kasir, mekanik.'],
                    ['type' => 'h', 'text' => 'Activity Log'],
                    ['type' => 'p', 'text' => 'Jejak semua aksi user — create, update, delete, login, logout, dengan timestamp.'],
                    ['type' => 'h', 'text' => 'API Tokens'],
                    ['type' => 'p', 'text' => 'Generate token untuk integrasi eksternal (mobile app, webhook).'],
                    ['type' => 'screenshot', 'file' => 'user-list.png', 'label' => 'Users', 'url' => '/admin/users', 'caption' => 'Daftar user — CRUD karyawan, assign role & cabang, aktif/nonaktif.'],
                    ['type' => 'screenshot', 'file' => 'role-list.png', 'label' => 'Roles & Permissions', 'url' => '/admin/roles', 'caption' => 'Role & permission — 5 role preset, permission granular per modul.'],
                    ['type' => 'screenshot', 'file' => 'activity-logs.png', 'label' => 'Activity Log', 'url' => '/admin/activity-logs', 'caption' => 'Activity log — jejak semua aksi user dengan timestamp.'],
                ],
            ],
            [
                'slug'  => 'menu-settings',
                'icon'  => 'fa-sliders',
                'title' => '16. Menu Settings',
                'lead'  => 'General, Invoice Layout, Payment Gateway, dan Backup & Restore.',
                'body'  => [
                    ['type' => 'p', 'text' => 'Grup <b>Settings</b> berisi konfigurasi aplikasi — profil bengkel, layout invoice, payment gateway, dan backup.'],
                    ['type' => 'h', 'text' => 'General Settings'],
                    ['type' => 'p', 'text' => 'Profil bengkel: nama, alamat, telepon, email, logo, jam operasional, dan zona waktu.'],
                    ['type' => 'h', 'text' => 'Invoice Layout'],
                    ['type' => 'p', 'text' => 'Atur tampilan invoice & gate pass: logo, footer, catatan, format nomor, dan tanda tangan.'],
                    ['type' => 'h', 'text' => 'Payment Gateway'],
                    ['type' => 'p', 'text' => 'Konfigurasi payment gateway (QRIS, Midtrans, dsb.) — mode sandbox/live, API key, dan link pembayaran.'],
                    ['type' => 'h', 'text' => 'Backup & Restore'],
                    ['type' => 'p', 'text' => 'Download backup SQL, riwayat backup, clear cache, optimize. Backup otomatis tiap jam 02:00 WIB.'],
                    ['type' => 'screenshot', 'file' => 'settings.png', 'label' => 'General Settings', 'url' => '/admin/settings', 'caption' => 'General settings — profil bengkel, logo, alamat, kontak, jam operasional.'],
                    ['type' => 'screenshot', 'file' => 'payment-gateways.png', 'label' => 'Payment Gateways', 'url' => '/admin/payment-gateways', 'caption' => 'Payment gateway — konfigurasi QRIS/transfer, mode sandbox/live, link pembayaran.'],
                ],
            ],
            [
                'slug'  => 'faq',
                'icon'  => 'fa-question-circle',
                'title' => '17. FAQ & Troubleshooting',
                'lead'  => 'Pertanyaan paling sering diajukan operator bengkel.',
                'body'  => [
                    ['type' => 'faq', 'items' => [
                        ['q' => 'Kenapa menu saya tidak muncul semua?', 'a' => 'Role Anda mungkin terbatas. Admin/super_admin punya semua menu. Cek di <b>Users & Security → Roles</b> permission apa yang dimiliki role Anda.'],
                        ['q' => 'Apa perbedaan 13 status workflow dengan yang lama?', 'a' => 'Workflow lama 6 step (Pending→Check In→Progress→QC→Ready→Delivered). Workflow BARU 13 step lebih detail: Booked → Checked In → Inspection → Waiting Approval → Approved → In Progress → Waiting Parts → QC → Ready → Invoiced → Paid → Released → Completed. Setiap tahap mencerminkan kondisi nyata di bengkel.'],
                        ['q' => 'Bagaimana cara auto-accounting bekerja?', 'a' => 'AutoJournalService otomatis generate journal entry setiap kali invoice diterbitkan atau pembayaran diterima. Tidak perlu input manual. Hasilnya bisa dilihat di <b>Finance & Accounting → Journal Entry</b>, lalu <b>Reports → General Ledger</b>, <b>P&L</b>, dan <b>Balance Sheet</b>.'],
                        ['q' => 'Stok minus, bagaimana?', 'a' => 'Lakukan <b>Stock Adjustment</b> dengan tipe Stock Opname. Input quantity fisik → submit → Manager approve → stok terkoreksi. Cek <b>Stock History</b> untuk lacak transaksi penyebab selisih.'],
                        ['q' => 'Bagaimana cara backup database?', 'a' => 'Buka <b>Settings → Backup & Restore</b>. Download SQL. Backup otomatis tiap jam 02:00 WIB.'],
                        ['q' => 'Apakah support WhatsApp notification?', 'a' => 'Ya. Isi WHATSAPP_API_URL dan WHATSAPP_API_KEY di .env. Gunakan <b>Campaign</b> di <b>CRM & Marketing</b> untuk blast massal. Notifikasi otomatis juga terkirim via WhatsApp untuk estimasi approval, service selesai, dan reminder.'],
                        ['q' => 'Bisa multi-cabang?', 'a' => 'Ya. Tambah cabang di <b>Operations → Branches</b>, pakai switcher di topbar. Semua data otomatis ter-filter per cabang.'],
                        ['q' => 'Bagaimana transfer stok antar gudang?', 'a' => 'Buka <b>Inventory → Warehouses → Transfer Stok</b>. Pilih dari gudang A ke gudang B. Stok otomatis pindah.'],
                        ['q' => 'Apa itu Recall CRM?', 'a' => 'Fitur di <b>CRM & Marketing</b> yang mendeteksi customer lama tidak service (3-6 bulan). Kirim reminder/promosi otomatis untuk mengajak kembali. Bisa segmentasi berdasarkan service terakhir, total spending, atau tipe kendaraan.'],
                        ['q' => 'Cara pakai digital signature?', 'a' => 'Buka <b>Operations → Gate Passes</b> → canvas untuk tanda tangan customer & teknisi. Support touch screen. Tersimpan sebagai gambar dan muncul di print gate pass.'],
                        ['q' => 'Bagaimana cara approval estimasi oleh customer?', 'a' => 'Saat service di status <b>Waiting Approval</b>, sistem kirim estimasi via WhatsApp/Email ke customer. Customer bisa klik link untuk approve/reject. Jika approved, status lanjut ke <b>Approved → In Progress</b>.'],
                        ['q' => 'Apa fungsi notification bell di topbar?', 'a' => 'Ikon lonceng menampilkan jumlah notifikasi belum dibaca. Klik untuk lihat daftar notifikasi real-time: service ready, pembayaran diterima, approval request, reminder service.'],
                        ['q' => 'Apa itu Bank Reconciliation (Rekonsiliasi Bank)?', 'a' => 'Fitur di <b>Finance & Accounting → Bank Reconciliation</b> untuk mencocokkan saldo bank di sistem dengan mutasi rekening riil. Tandai transaksi clear/unclear dan hitung selisih — memudahkan audit bulanan.'],
                        ['q' => 'Bagaimana cara membuat anggaran (Budget)?', 'a' => 'Buka <b>Finance & Accounting → Budget</b>. Buat anggaran per kategori dan periode. Sistem membandingkan realisasi pengeluaran vs anggaran sehingga Anda bisa kontrol pengeluaran.'],
                        ['q' => 'Apa fungsi Skill Matrix teknisi?', 'a' => 'Di <b>Technicians → Skill Matrix</b>, Anda memetakan kompetensi tiap teknisi (mesin, kelistrikan, AC, body) beserta level keahlian. Ini membantu assign teknisi yang tepat ke service tertentu.'],
                        ['q' => 'Apa bedanya Purchase Requisition dan Purchase Order?', 'a' => 'Purchase Requisition adalah permintaan pengadaan internal (dari teknisi/service yang butuh parts). Setelah disetujui, requisition diubah menjadi Purchase Order ke supplier. Ini memberi kontrol approval sebelum pembelian.'],
                        ['q' => 'Bagaimana retur penjualan (Sell Return) bekerja?', 'a' => 'Di <b>Sales & POS → Sell Returns</b>, buat retur barang dari customer. Stok otomatis bertambah kembali, refund tercatat, dan history lengkap tersimpan untuk audit.'],
                        ['q' => 'Apa itu klaim asuransi dan klaim supplier?', 'a' => 'Klaim Asuransi untuk mengelola klaim asuransi kendaraan customer (dokumen, status, pembayaran dari asuransi). Klaim Supplier untuk klaim sparepart cacat/rusak ke supplier, terkait langsung dengan purchase & stok.'],
                    ]],
                ],
            ],
            [
                'slug'  => 'flow-service',
                'icon'  => 'fa-code-branch',
                'title' => '18. Data Flow: Service (Booking → Bayar)',
                'lead'  => 'Bagaimana data mengalir dari customer datang sampai bayar lunas — lengkap dengan screenshot tiap tahap.',
                'body'  => [
                    ['type' => 'note', 'text' => '<b>Alur data:</b><br>Booking → Check-in → Inspection → Job Card → Estimasi → Approval WA → In Progress → Parts terpakai → QC → Ready → Invoice → Payment → Bayar Lunas → Gate Pass → Completed'],
                    ['type' => 'ol', 'items' => [
                        'Customer datang/booking → data masuk ke <b>Booking</b> (nama, HP, kendaraan, jadwal).',
                        'Check-in → <b>Service</b> dibuat, status <b>Checked In</b>, odometer masuk tercatat.',
                        'Inspeksi → <b>Observation Points</b> terisi (checklist + foto), status <b>Inspection</b>.',
                        'Estimasi → pilih parts dari <b>Inventory</b> + jasa, hitung total, status <b>Waiting Approval</b>.',
                        'Approval → customer approve via WA, status <b>Approved</b> → <b>In Progress</b>.',
                        'Teknisi pakai parts → <b>StockRecord</b> berkurang otomatis + <b>StockHistory</b> tercatat.',
                        'QC → checklist final, status <b>QC</b> → <b>Ready</b>.',
                        '<b>Invoice</b> diterbitkan (parts + jasa + diskon + pajak), status <b>Invoiced</b>.',
                        '<b>Payment</b> diterima → <b>paid_amount</b> bertambah, status <b>Paid</b>.',
                        'Lunas → <b>Income</b> tercatat + <b>AutoJournal</b> generate jurnal + <b>Loyalty Points</b> bertambah.',
                        '<b>Gate Pass</b> dibuat + digital signature → status <b>Released</b> → <b>Completed</b>.',
                    ]],
                    ['type' => 'screenshot', 'file' => 'service-create.png', 'label' => 'Check-in Service', 'url' => '/admin/services/create', 'caption' => 'Titik masuk data: customer, kendaraan, keluhan, odometer.'],
                    ['type' => 'screenshot', 'file' => 'jobcard-list.png', 'label' => 'Job Card + Estimasi', 'url' => '/admin/jobcards', 'caption' => 'Job card + estimasi biaya & pekerjaan.'],
                    ['type' => 'screenshot', 'file' => 'invoice-list.png', 'label' => 'Invoice', 'url' => '/admin/invoices', 'caption' => 'Invoice dari service — parts + jasa + diskon + pajak.'],
                ],
            ],
            [
                'slug'  => 'flow-inventory',
                'icon'  => 'fa-arrow-right-arrow-left',
                'title' => '19. Data Flow: Inventory (Parts & Stok)',
                'lead'  => 'Bagaimana sparepart mengalir: masuk (purchase) dan keluar (service/POS), dengan auto journal.',
                'body'  => [
                    ['type' => 'note', 'text' => '<b>Stok masuk:</b> Purchase Order → Mark Received → StockRecord bertambah → StockHistory → AutoJournal (Debit Inventory, Credit Utang/Kas)<br><b>Stok keluar:</b> Service/POS pakai parts → StockRecord berkurang → StockHistory → biaya masuk ke invoice'],
                    ['type' => 'ol', 'items' => [
                        'Beli sparepart → <b>Purchase Order</b> ke supplier.',
                        '<b>Mark Received</b> → <b>StockRecord</b> bertambah + <b>StockHistory</b> (type purchase).',
                        '<b>AutoJournal</b> → Debit <b>Inventory (1200)</b>, Credit <b>Accounts Payable/Kas</b>.',
                        'Teknisi pakai parts di service → <b>StockRecord</b> berkurang + <b>StockHistory</b> (type usage).',
                        'Jual sparepart via <b>POS</b> → <b>StockRecord</b> berkurang + <b>StockHistory</b> (type pos).',
                        '<b>Stock Adjustment</b> untuk koreksi selisih (approval workflow).',
                        '<b>Reservasi Parts</b> mengunci stok untuk service tertentu (reserved).',
                    ]],
                    ['type' => 'screenshot', 'file' => 'purchase-list.png', 'label' => 'Purchase Orders', 'url' => '/admin/purchases', 'caption' => 'Stok masuk via purchase order → received → auto tambah stok.'],
                    ['type' => 'screenshot', 'file' => 'product-list.png', 'label' => 'Products & Stok', 'url' => '/admin/products', 'caption' => 'Stok sparepart — harga beli/jual, stok per gudang, reorder alert.'],
                    ['type' => 'screenshot', 'file' => 'stock-adjustments.png', 'label' => 'Stock Adjustment', 'url' => '/admin/stock-adjustments', 'caption' => 'Koreksi stok dengan approval workflow.'],
                ],
            ],
            [
                'slug'  => 'flow-accounting',
                'icon'  => 'fa-calculator',
                'title' => '20. Data Flow: Accounting (Auto Journal)',
                'lead'  => 'Setiap transaksi otomatis menghasilkan jurnal akuntansi — dari invoice, pembayaran, sampai laporan.',
                'body'  => [
                    ['type' => 'note', 'text' => '<b>Alur:</b> Invoice dibayar → Income tercatat → AutoJournal (Debit Kas/Bank, Credit Pendapatan) → JournalEntry + Line → General Ledger → P&L → Balance Sheet'],
                    ['type' => 'ol', 'items' => [
                        '<b>Invoice lunas</b> → <b>Income</b> tercatat otomatis.',
                        '<b>AutoJournalService</b> → buat <b>JournalEntry</b> + 2 <b>JournalEntryLine</b> (Debit Kas 1000, Credit Service Revenue 4000).',
                        '<b>Purchase received</b> → Debit Inventory (1200), Credit Accounts Payable (2000).',
                        '<b>Expense</b> → Debit General Expense (5000), Credit Kas (1000).',
                        'Semua jurnal masuk <b>Journal Entry</b> — bisa dicek & diaudit.',
                        '<b>Reports</b> membaca journal: <b>General Ledger</b>, <b>P&L</b> (pendapatan - beban), <b>Balance Sheet</b> (aset = liabilitas + ekuitas).',
                    ]],
                    ['type' => 'screenshot', 'file' => 'coa-list.png', 'label' => 'Chart of Accounts', 'url' => '/admin/finance/coa', 'caption' => 'COA — akun asset/liability/equity/income/expense.'],
                    ['type' => 'screenshot', 'file' => 'journal-list.png', 'label' => 'Journal Entries', 'url' => '/admin/finance/journal', 'caption' => 'Journal entry — debit/kredit seimbang dari AutoJournal.'],
                    ['type' => 'screenshot', 'file' => 'report-general-ledger.png', 'label' => 'General Ledger', 'url' => '/admin/reports/general-ledger', 'caption' => 'General Ledger — semua mutasi per akun.'],
                    ['type' => 'screenshot', 'file' => 'report-profit-loss.png', 'label' => 'Profit & Loss', 'url' => '/admin/reports/profit-loss', 'caption' => 'Laba rugi — pendapatan vs beban.'],
                ],
            ],
            [
                'slug'  => 'flow-pos',
                'icon'  => 'fa-cash-register',
                'title' => '21. Data Flow: POS & Loyalty',
                'lead'  => 'Alur penjualan kasir — dari buka sesi sampai tutup sesi, dengan loyalty poin otomatis.',
                'body'  => [
                    ['type' => 'note', 'text' => '<b>Alur:</b> Buka Sesi (saldo awal) → Scan/Pilih sparepart → Checkout → Invoice (type pos) + Payment + Stock berkurang + Income + Loyalty poin → Tutup Sesi (hitung fisik uang)'],
                    ['type' => 'ol', 'items' => [
                        '<b>Buka Sesi POS</b> → input saldo awal kasir.',
                        'Scan/pilih produk → keranjang → pilih customer (opsional) + metode bayar.',
                        '<b>Checkout</b> → Invoice (invoice_type=pos) + PaymentRecord + StockRecord berkurang.',
                        'Otomatis → <b>Income</b> + <b>AutoJournal</b> + <b>Loyalty Points</b> ke customer.',
                        '<b>Voucher</b> bisa dipakai → diskon + VoucherUsage tercatat.',
                        '<b>Tutup Sesi</b> → hitung fisik uang (denomination) → sistem hitung selisih.',
                    ]],
                    ['type' => 'screenshot', 'file' => 'pos-terminal.png', 'label' => 'POS Terminal', 'url' => '/admin/pos', 'caption' => 'Terminal kasir — scan, checkout, voucher, split payment.'],
                    ['type' => 'screenshot', 'file' => 'pos-sessions.png', 'label' => 'POS Sessions', 'url' => '/admin/pos/sessions', 'caption' => 'Riwayat sesi — buka/tutup, saldo, selisih.'],
                    ['type' => 'screenshot', 'file' => 'loyalty-list.png', 'label' => 'Loyalty Points', 'url' => '/admin/loyalty', 'caption' => 'Loyalty poin customer — bertambah otomatis tiap transaksi.'],
                ],
            ],
            [
                'slug'  => 'flow-warranty',
                'icon'  => 'fa-shield-halved',
                'title' => '22. Data Flow: Warranty & Klaim',
                'lead'  => 'Alur garansi — dari claim customer sampai klaim ke supplier/asuransi.',
                'body'  => [
                    ['type' => 'note', 'text' => '<b>Alur:</b> Customer klaim garansi → WarrantyClaim (dari InvoiceItem) → cek garansi parts → Klaim Supplier / Klaim Asuransi'],
                    ['type' => 'ol', 'items' => [
                        'Customer klaim → <b>Warranty Claim</b> dibuat, terhubung ke <b>Invoice Item</b> (parts yang dibeli).',
                        'Cek <b>garansi parts</b> → masih berlaku atau habis (warranty_expiry per item).',
                        'Jika parts cacat dari supplier → <b>Supplier Claim</b> (klaim ke supplier).',
                        'Jika kendaraan customer → <b>Insurance Claim</b> (klaim ke asuransi).',
                        '<b>Recall</b> → pemberitahuan recall parts/merk tertentu.',
                    ]],
                    ['type' => 'screenshot', 'file' => 'warranty-list.png', 'label' => 'Warranty Claims', 'url' => '/admin/warranty-claims', 'caption' => 'Klaim garansi — terhubung ke invoice item & parts.'],
                    ['type' => 'screenshot', 'file' => 'insurance-list.png', 'label' => 'Insurance Claims', 'url' => '/admin/insurance-claims', 'caption' => 'Klaim asuransi kendaraan customer.'],
                    ['type' => 'screenshot', 'file' => 'supplier-claims-list.png', 'label' => 'Supplier Claims', 'url' => '/admin/supplier-claims', 'caption' => 'Klaim sparepart cacat ke supplier.'],
                ],
            ],
            [
                'slug'  => 'flow-technician',
                'icon'  => 'fa-user-gear',
                'title' => '23. Data Flow: Teknisi & Komisi',
                'lead'  => 'Alur teknisi — dari assign job sampai komisi dibayar, dengan time tracking.',
                'body'  => [
                    ['type' => 'note', 'text' => '<b>Alur:</b> Service assign teknisi → Timer start/finish → Service selesai → Komisi otomatis dihitung → Mark Paid'],
                    ['type' => 'ol', 'items' => [
                        '<b>Service Advisor</b> assign teknisi + service advisor ke service.',
                        'Teknisi <b>start timer</b> saat mulai kerja, <b>finish</b> saat selesai (durasi tercatat).',
                        '<b>Skill Matrix</b> memastikan teknisi punya kompetensi untuk job.',
                        'Service selesai → <b>komisi otomatis dihitung</b> (persentase dari charge, dibagi jumlah teknisi).',
                        'Komisi di <b>Commission</b> → filter, laporan, <b>mark paid</b> batch.',
                    ]],
                    ['type' => 'screenshot', 'file' => 'commission-list.png', 'label' => 'Commissions', 'url' => '/admin/commissions', 'caption' => 'Komisi teknisi — dihitung otomatis, mark paid.'],
                    ['type' => 'screenshot', 'file' => 'technician-skills.png', 'label' => 'Skill Matrix', 'url' => '/admin/technician-skills', 'caption' => 'Peta kompetensi teknisi.'],
                    ['type' => 'screenshot', 'file' => 'report-technician.png', 'label' => 'Technician Report', 'url' => '/admin/reports/technician', 'caption' => 'Laporan produktivitas teknisi.'],
                ],
            ],
            [
                'slug'  => 'flow-booking',
                'icon'  => 'fa-calendar-check',
                'title' => '24. Data Flow: Booking → Service',
                'lead'  => 'Alur booking online — dari customer pesan jadwal sampai dikonversi jadi service.',
                'body'  => [
                    ['type' => 'note', 'text' => '<b>Alur:</b> Customer booking (nama/HP/kendaraan/jadwal/kategori) → Status Pending → Admin konfirmasi → Convert → Service + Customer + Vehicle (auto)'],
                    ['type' => 'ol', 'items' => [
                        'Customer isi <b>Booking Form</b> (public) — nama, HP, plat, kendaraan, jadwal, kategori service.',
                        'Booking masuk <b>status Pending</b>, muncul di daftar admin + kalender.',
                        'Admin <b>konfirmasi</b> → status Confirmed (bisa assign teknisi + cek ketersediaan).',
                        '<b>Convert ke Service</b> → otomatis buat <b>Customer</b> (by HP) + <b>Vehicle</b> (by plat) + <b>Service</b> (kategori & keluhan dibawa).',
                        'Lanjut ke workflow 13-status normal (Check-in → dst).',
                    ]],
                    ['type' => 'screenshot', 'file' => 'booking-list.png', 'label' => 'Booking List', 'url' => '/admin/bookings', 'caption' => 'Daftar booking — konfirmasi, assign teknisi, convert ke service.'],
                    ['type' => 'screenshot', 'file' => 'customer-list.png', 'label' => 'Customer (auto)', 'url' => '/admin/customers', 'caption' => 'Customer otomatis terbuat dari booking (by nomor HP).'],
                ],
            ],
            [
                'slug'  => 'flow-requisition',
                'icon'  => 'fa-clipboard-list',
                'title' => '25. Data Flow: Purchase Requisition → PO',
                'lead'  => 'Alur permintaan pembelian internal — dari teknisi butuh parts sampai jadi purchase order.',
                'body'  => [
                    ['type' => 'note', 'text' => '<b>Alur:</b> Teknisi butuh parts → Requisition (draft) → Submit → Manager Approve/Reject → Convert → Purchase Order → Mark Received → Stok bertambah'],
                    ['type' => 'ol', 'items' => [
                        'Teknisi/staff buat <b>Purchase Requisition</b> (parts yang dibutuhkan + qty).',
                        'Submit → status <b>submitted</b> (menunggu approval).',
                        'Manager <b>approve</b> (atau reject dengan alasan) → status <b>approved</b>.',
                        '<b>Convert</b> → otomatis buat <b>Purchase Order</b> ke supplier (item + harga beli).',
                        'PO <b>Mark Received</b> → stok bertambah + journal otomatis.',
                    ]],
                    ['type' => 'screenshot', 'file' => 'purchase-requisition-list.png', 'label' => 'Purchase Requisitions', 'url' => '/admin/purchase-requisitions', 'caption' => 'Permintaan pembelian internal — approval workflow.'],
                    ['type' => 'screenshot', 'file' => 'purchase-list.png', 'label' => 'Purchase Orders', 'url' => '/admin/purchases', 'caption' => 'PO dari requisition → received → stok bertambah.'],
                ],
            ],
            [
                'slug'  => 'flow-return',
                'icon'  => 'fa-rotate-left',
                'title' => '26. Data Flow: Retur (Penjualan & Pembelian)',
                'lead'  => 'Alur retur — barang balik ke stok baik dari customer maupun ke supplier.',
                'body'  => [
                    ['type' => 'note', 'text' => '<b>Sell Return (customer):</b> Customer retur barang → Sell Return + item → Stok bertambah + StockHistory (sell_return) + Refund<br><b>Purchase Return (supplier):</b> Barang dikembalikan ke supplier → Stok berkurang + StockHistory (return)'],
                    ['type' => 'ol', 'items' => [
                        '<b>Sell Return</b>: customer kembalikan sparepart yang dibeli → pilih sale/invoice/barang.',
                        'Stok otomatis <b>bertambah kembali</b> + StockHistory (type sell_return) + refund dihitung.',
                        '<b>Purchase Return</b>: barang cacat dikembalikan ke supplier → stok berkurang.',
                        'StockHistory (type return) mencatat kedua arah untuk audit.',
                    ]],
                    ['type' => 'screenshot', 'file' => 'sell-return-list.png', 'label' => 'Sell Returns', 'url' => '/admin/sell-returns', 'caption' => 'Retur dari customer — stok balik + refund.'],
                    ['type' => 'screenshot', 'file' => 'purchase-return.png', 'label' => 'Purchase Returns', 'url' => '/admin/purchases/return', 'caption' => 'Retur ke supplier — stok berkurang + history.'],
                ],
            ],
            [
                'slug'  => 'flow-fleet',
                'icon'  => 'fa-truck-fast',
                'title' => '27. Data Flow: Fleet Contract',
                'lead'  => 'Alur kontrak servis rutin perusahaan/fleet — interval servis + deteksi jatuh tempo.',
                'body'  => [
                    ['type' => 'note', 'text' => '<b>Alur:</b> Buat Fleet Contract (customer + interval servis) → Daftarkan kendaraan → Sistem deteksi jatuh tempo (last service + interval) → Buat service/booking'],
                    ['type' => 'ol', 'items' => [
                        'Buat <b>Fleet Contract</b> untuk perusahaan (interval servis: hari & KM).',
                        'Daftarkan <b>kendaraan</b> yang terikat kontrak.',
                        'Sistem <b>deteksi jatuh tempo</b> — kendaraan yang sudah waktunya servis berdasarkan last service + interval.',
                        'Buat <b>service/booking</b> untuk kendaraan yang jatuh tempo.',
                    ]],
                    ['type' => 'screenshot', 'file' => 'fleet-contract-list.png', 'label' => 'Fleet Contracts', 'url' => '/admin/fleet-contracts', 'caption' => 'Kontrak fleet — interval servis, daftar kendaraan, deteksi jatuh tempo.'],
                ],
            ],
            [
                'slug'  => 'flow-voucher',
                'icon'  => 'fa-ticket',
                'title' => '28. Data Flow: Voucher & Loyalty',
                'lead'  => 'Alur promo & poin — dari buat voucher sampai dipakai, plus loyalty poin otomatis.',
                'body'  => [
                    ['type' => 'note', 'text' => '<b>Voucher:</b> Buat voucher (diskon/persen, min transaksi, masa berlaku) → Customer masukkan kode di POS → Validasi → Diskon + VoucherUsage<br><b>Loyalty:</b> Invoice lunas → Poin otomatis (1 poin / Rp 1.000) → Tier naik (bronze→platinum)'],
                    ['type' => 'ol', 'items' => [
                        'Buat <b>Voucher</b> — kode, diskon (persen/fixed), min pembelian, masa berlaku, kuota.',
                        'Customer pakai kode di <b>POS</b> → validasi → diskon diterapkan + VoucherUsage tercatat.',
                        '<b>Loyalty</b>: tiap invoice lunas → poin otomatis ke customer.',
                        'Tier membership naik otomatis (bronze → silver → gold → platinum) berdasarkan total poin.',
                    ]],
                    ['type' => 'screenshot', 'file' => 'voucher-list.png', 'label' => 'Vouchers', 'url' => '/admin/vouchers', 'caption' => 'Voucher promo — kode, diskon, masa berlaku, kuota.'],
                    ['type' => 'screenshot', 'file' => 'loyalty-list.png', 'label' => 'Loyalty', 'url' => '/admin/loyalty', 'caption' => 'Loyalty poin & tier membership customer.'],
                ],
            ],
            [
                'slug'  => 'flow-notification',
                'icon'  => 'fa-bell-concierge',
                'title' => '29. Data Flow: Notifikasi & Reminder',
                'lead'  => 'Alur notifikasi multi-channel — dari template sampai terkirim via WA/Email/SMS.',
                'body'  => [
                    ['type' => 'note', 'text' => '<b>Alur:</b> Buat Template (variabel) → Event trigger (service ready/payment/reminder) → Queue (notification_queue) → Scheduler proses tiap 5 menit → Kirim WA/Email/SMS → Log'],
                    ['type' => 'ol', 'items' => [
                        'Buat <b>Notification Template</b> dengan variabel ({customer_name}, {plate}, {next_service_date}).',
                        'Event memicu notifikasi: service ready, invoice dibuat, reminder service, approval estimasi.',
                        'Notifikasi masuk <b>queue</b> → diproses scheduler tiap 5 menit.',
                        'Kirim via <b>WhatsApp / Email / SMS</b> sesuai channel template.',
                        'Semua tercatat di <b>Notification Log</b> (status sent/failed).',
                    ]],
                    ['type' => 'screenshot', 'file' => 'notification-templates.png', 'label' => 'Templates', 'url' => '/admin/notification-templates', 'caption' => 'Template notifikasi multi-channel.'],
                    ['type' => 'screenshot', 'file' => 'reminder-list.png', 'label' => 'Reminders', 'url' => '/admin/reminders', 'caption' => 'Reminder service otomatis — H-7, H-3, H-1.'],
                ],
            ],
            [
                'slug'  => 'flow-bank',
                'icon'  => 'fa-building-columns',
                'title' => '30. Data Flow: Bank & Budget',
                'lead'  => 'Alur rekonsiliasi bank & anggaran — cocokkan saldo sistem vs riil, kontrol pengeluaran.',
                'body'  => [
                    ['type' => 'note', 'text' => '<b>Bank Recon:</b> Bank Account → Rekonsiliasi (saldo awal + income − expense) → Bandingkan statement → Selisih<br><b>Budget:</b> Set budget (kategori/periode/cabang) → Sistem bandingkan realisasi vs anggaran → Variance'],
                    ['type' => 'ol', 'items' => [
                        'Buat <b>Bank Account</b> (rekening + saldo awal).',
                        '<b>Rekonsiliasi</b>: sistem hitung saldo akhir (saldo awal + income − expense) vs saldo statement → selisih.',
                        '<b>Budget</b>: set anggaran per kategori (revenue/expense) per periode per cabang.',
                        'Sistem bandingkan <b>realisasi</b> (Income/Expense) vs <b>anggaran</b> → variance terkontrol.',
                    ]],
                    ['type' => 'screenshot', 'file' => 'bank-account-list.png', 'label' => 'Bank Accounts', 'url' => '/admin/bank-accounts', 'caption' => 'Rekening bank — saldo, jenis rekening.'],
                    ['type' => 'screenshot', 'file' => 'bank-reconciliation-list.png', 'label' => 'Bank Reconciliation', 'url' => '/admin/bank-reconciliations', 'caption' => 'Rekonsiliasi bank — saldo sistem vs statement.'],
                    ['type' => 'screenshot', 'file' => 'budget-list.png', 'label' => 'Budgets', 'url' => '/admin/budgets', 'caption' => 'Anggaran — realisasi vs anggaran per periode.'],
                ],
            ],
        ];
    }
}
