<?php

namespace App\Support;

/**
 * Curated public SEO registry. A slug is indexable only when it is declared
 * here; arbitrary URL strings never become landing pages.
 */
final class PseoPageRegistry
{
    /** @return array<string, array<string, mixed>> */
    public static function pages(): array
    {
        $pages = [
            'source-code-aplikasi-bengkel' => self::page('source_code', 'Source Code Aplikasi Bengkel Laravel | Mulai Rp 7 Juta', 'Source Code Aplikasi Bengkel Profesional', 'Miliki sistem bengkel sendiri dengan full source code yang dapat disesuaikan untuk operasional bengkel mobil maupun motor.', 'FULL SOURCE CODE', 'Banyak bengkel membutuhkan sistem yang mengikuti proses mereka, bukan sekadar pencatatan generik.', 'Gunakan aplikasi manajemen bengkel berbasis web dengan modul operasional dari customer masuk sampai laporan.', ['sistem dapat dikembangkan sesuai kebutuhan', 'customer dan kendaraan tersimpan terpusat', 'estimasi, pekerjaan, inventory, QC, invoice, dan laporan saling terhubung', 'source code disediakan sesuai paket dan lisensi yang disepakati'], ['customers', 'vehicles', 'estimates', 'jobcards', 'inventory', 'qc', 'invoice', 'reports'], 'Pemilik bengkel, developer, agency, dan tim IT yang membutuhkan fondasi aplikasi siap dikembangkan.', ['aplikasi-bengkel', 'harga-aplikasi-bengkel', 'aplikasi-bengkel-laravel', 'aplikasi-bengkel-white-label']),
            'aplikasi-bengkel' => self::page('core', 'Aplikasi Bengkel Profesional Berbasis Web | Bisa Custom', 'Aplikasi Bengkel Profesional untuk Operasional yang Lebih Teratur', 'Kelola customer, kendaraan, check-in, temuan, estimasi, pekerjaan mekanik, inventory, QC, invoice, dan laporan dalam satu alur kerja.', 'SOFTWARE MANAJEMEN BENGKEL', 'Data customer, pekerjaan, sparepart, dan dokumen sering tersebar di banyak catatan.', 'Satu sistem membantu tim menjaga status pekerjaan dan informasi customer tetap tersambung.', ['alur kerja bengkel lebih terstruktur', 'informasi customer dan kendaraan mudah ditelusuri', 'estimasi dapat dibagikan sebelum pekerjaan dilakukan', 'laporan membantu pemilik mengevaluasi usaha'], ['booking', 'customers', 'checkin', 'findings', 'estimates', 'work', 'inventory', 'invoice', 'reports'], 'Bengkel mobil, bengkel motor, dan workshop general repair.', ['source-code-aplikasi-bengkel', 'harga-aplikasi-bengkel', 'aplikasi-bengkel-estimasi', 'aplikasi-bengkel-inventory']),
            'software-bengkel' => self::page('core', 'Software Bengkel untuk Manajemen Service & Sparepart', 'Software Bengkel untuk Mengelola Operasional Harian', 'Software bengkel berbasis web untuk menghubungkan meja penerimaan, mekanik, inventory, QC, kasir, dan pemilik usaha.', 'SISTEM TERINTEGRASI', 'Software yang hanya mencatat invoice belum tentu membantu proses diagnosis dan pengerjaan.', 'Gunakan alur yang memetakan pekerjaan sejak booking atau walk-in sampai kendaraan siap diserahkan.', ['workflow lintas tim lebih jelas', 'sparepart dan jasa tersusun dalam konteks pekerjaan', 'dokumen customer-facing lebih konsisten', 'fondasi digitalisasi dapat dikembangkan'], ['booking', 'checkin', 'work', 'parts', 'inventory', 'qc', 'invoice', 'reports'], 'Pemilik usaha yang ingin mengganti pencatatan manual dengan software bengkel terstruktur.', ['source-code-aplikasi-bengkel', 'harga-software-bengkel', 'aplikasi-bengkel-multi-user']),
            'sistem-bengkel' => self::page('core', 'Sistem Bengkel Berbasis Web untuk Operasional Terpadu', 'Sistem Bengkel yang Menyatukan Data dan Pekerjaan', 'Bangun operasional bengkel yang lebih mudah dipantau dengan sistem untuk customer, kendaraan, temuan, pekerjaan, stok, QC, invoice, dan histori service.', 'ALUR TERHUBUNG', 'Perubahan status pekerjaan sulit dipantau jika setiap bagian memakai catatan berbeda.', 'Sistem bengkel menyimpan konteks transaksi di satu tempat dengan hak akses sesuai peran.', ['status pekerjaan lebih jelas', 'handover antar bagian lebih rapi', 'dokumen dan histori tersimpan', 'siap disesuaikan dengan SOP bengkel'], ['customers', 'vehicles', 'findings', 'work', 'inventory', 'qc', 'invoice', 'history'], 'Bengkel yang sedang membangun SOP digital dan membutuhkan visibilitas operasional.', ['source-code-aplikasi-bengkel', 'aplikasi-bengkel-laporan', 'aplikasi-bengkel-role-management']),
            'erp-bengkel' => self::page('core', 'ERP Bengkel untuk Customer, Service, Inventory & Laporan', 'ERP Bengkel untuk Mengelola Operasional dari Awal sampai Selesai', 'ERP bengkel berbasis web yang mencakup penerimaan kendaraan, inspeksi, estimasi, work order, sparepart, QC, invoice, pembayaran, dan laporan.', 'ERP BENGKEL', 'Pertumbuhan transaksi membuat koordinasi pekerjaan, stok, dan keuangan sulit dilakukan secara terpisah.', 'ERP membantu pemilik dan tim melihat proses utama dalam satu sistem dengan akses sesuai peran.', ['satu alur dari check-in ke selesai', 'modul operasional saling terhubung', 'role management untuk membatasi akses', 'laporan membantu keputusan bisnis'], ['booking', 'checkin', 'estimates', 'work', 'inventory', 'qc', 'invoice', 'payments', 'roles', 'reports'], 'Workshop yang membutuhkan fondasi ERP dan rencana pengembangan bertahap.', ['source-code-aplikasi-bengkel', 'aplikasi-bengkel-multi-cabang', 'aplikasi-bengkel-laporan']),
            'aplikasi-workshop' => self::page('core', 'Aplikasi Workshop Otomotif Berbasis Web', 'Aplikasi Workshop untuk Service dan Pekerjaan Otomotif', 'Kelola workshop otomotif dengan sistem yang mendukung customer, kendaraan, pekerjaan teknisi, parts, quality control, dan dokumen komersial.', 'WORKSHOP OTOMOTIF', 'Workshop membutuhkan alur fleksibel untuk berbagai jenis pekerjaan dan kendaraan.', 'Aplikasi workshop memberi struktur kerja yang dapat dikembangkan mengikuti kebutuhan operasional.', ['mendukung pekerjaan mobil dan motor', 'pencatatan pekerjaan lebih konsisten', 'informasi parts dan jasa tersusun', 'dokumen siap dibagikan ke customer'], ['customers', 'vehicles', 'findings', 'estimates', 'jobcards', 'parts', 'qc', 'invoice'], 'Workshop otomotif dan general repair yang ingin memakai aplikasi web.', ['source-code-aplikasi-bengkel', 'aplikasi-workshop-otomotif', 'aplikasi-bengkel-mobil']),
            'software-workshop' => self::page('core', 'Software Workshop Otomotif yang Bisa Dikustomisasi', 'Software Workshop untuk Alur Kerja yang Sesuai SOP', 'Software workshop untuk membantu tim penerimaan, mekanik, inventory, QC, dan kasir bekerja dalam alur yang terdokumentasi.', 'WORKSHOP SOFTWARE', 'Setiap workshop memiliki SOP, struktur tim, dan kebutuhan laporan yang berbeda.', 'Mulai dari workflow yang sudah tersedia lalu konsultasikan penyesuaian yang diperlukan.', ['alur kerja menjadi dasar SOP digital', 'modul dapat diprioritaskan', 'akses pengguna dapat diatur', 'mendukung pengembangan lanjutan'], ['workflow', 'roles', 'estimates', 'work', 'inventory', 'qc', 'invoice'], 'Pemilik workshop yang membutuhkan software fleksibel untuk pertumbuhan bisnis.', ['source-code-aplikasi-bengkel', 'aplikasi-bengkel-bisa-custom', 'aplikasi-bengkel-role-management']),
            'harga-aplikasi-bengkel' => self::page('price', 'Harga Aplikasi Bengkel Profesional | Source Code Tersedia', 'Harga Aplikasi Bengkel & Source Code', 'Harga aplikasi bengkel profesional mulai Rp 7.000.000. Harga akhir menyesuaikan customisasi, branding, integrasi, deployment, dan modul tambahan.', 'HARGA TRANSPARAN', 'Memilih software tanpa memahami cakupan source code dan kebutuhan implementasi dapat membuat biaya sulit diperkirakan.', 'Mulai dari paket dasar yang jelas, kemudian konsultasikan kebutuhan implementasi dan pengembangan Anda.', ['harga mulai Rp 7.000.000', 'source code sesuai paket dan lisensi', 'branding dan custom workflow dapat dibahas', 'konsultasi kebutuhan sebelum penawaran akhir'], ['source_code', 'customization', 'deployment', 'reports'], 'Pemilik bengkel atau perusahaan yang sedang membandingkan investasi software.', ['source-code-aplikasi-bengkel', 'aplikasi-bengkel-laravel', 'aplikasi-bengkel-white-label']),
            'harga-software-bengkel' => self::page('price', 'Harga Software Bengkel Berbasis Web | Mulai Rp 7 Juta', 'Berapa Harga Software Bengkel?', 'Software bengkel berbasis web tersedia mulai Rp 7.000.000 untuk kebutuhan source code dan implementasi yang dapat dikonsultasikan.', 'PERENCANAAN INVESTASI', 'Harga software tidak hanya ditentukan oleh jumlah halaman, tetapi juga workflow, integrasi, branding, dan deployment.', 'Gunakan harga awal ini sebagai dasar percakapan penawaran yang sesuai.', ['harga awal mudah dipahami', 'customisasi dibahas berdasarkan kebutuhan nyata', 'teknologi web mudah diakses tim', 'CTA langsung untuk konsultasi'], ['source_code', 'customization', 'deployment', 'workflow'], 'Pemilik workshop yang sedang menyusun anggaran digitalisasi.', ['harga-aplikasi-bengkel', 'source-code-aplikasi-bengkel', 'aplikasi-bengkel-bisa-custom']),
            'harga-source-code-aplikasi-bengkel' => self::page('price', 'Harga Source Code Aplikasi Bengkel | Mulai Rp 7 Juta', 'Harga Source Code Aplikasi Bengkel', 'Dapatkan informasi awal harga source code aplikasi bengkel mulai Rp 7.000.000, lalu sesuaikan penawaran dengan lisensi, customisasi, integrasi, dan deployment.', 'SOURCE CODE & HARGA', 'Pembeli source code perlu mengetahui bagian paket dan pekerjaan tambahan yang disepakati terpisah.', 'Konsultasikan kebutuhan teknis dan bisnis agar ruang lingkup pembelian jelas sejak awal.', ['mulai Rp 7.000.000', 'source code dan database sesuai paket', 'opsi custom dan white-label dapat dibahas', 'dukungan implementasi mengikuti kesepakatan'], ['source_code', 'customization', 'deployment'], 'Developer, agency, dan pemilik bengkel yang menginginkan kontrol lebih besar.', ['source-code-aplikasi-bengkel', 'source-code-aplikasi-bengkel-laravel', 'aplikasi-bengkel-white-label']),
            'aplikasi-bengkel-harga-7-juta' => self::page('price', 'Aplikasi Bengkel Harga 7 Juta | Mulai Rp 7.000.000', 'Aplikasi Bengkel dengan Harga Mulai Rp 7.000.000', 'Harga mulai Rp 7.000.000 untuk aplikasi bengkel profesional dengan source code yang dapat dikonsultasikan sesuai kebutuhan implementasi.', 'MULAI RP 7 JUTA', 'Bengkel membutuhkan kepastian kisaran investasi sebelum meminta demo atau customisasi.', 'Tampilkan kebutuhan utama Anda dan gunakan harga awal sebagai dasar percakapan penawaran.', ['harga mulai Rp 7.000.000', 'fitur operasional inti tersedia', 'harga akhir mengikuti ruang lingkup', 'konsultasi tanpa komitmen pembelian'], ['source_code', 'workflow', 'estimates', 'inventory', 'invoice'], 'Pemilik bengkel yang mencari aplikasi pada kisaran investasi Rp7 juta.', ['harga-aplikasi-bengkel', 'source-code-aplikasi-bengkel', 'aplikasi-bengkel-inventory']),
            'aplikasi-bengkel-bisa-custom' => self::page('customization', 'Aplikasi Bengkel Bisa Custom untuk SOP Bisnis Anda', 'Aplikasi Bengkel yang Bisa Disesuaikan dengan Workflow Anda', 'Gunakan aplikasi bengkel sebagai fondasi, lalu bahas penyesuaian workflow, branding, integrasi, dan deployment berdasarkan proses bisnis Anda.', 'FLEKSIBEL UNTUK SOP', 'Aplikasi siap pakai tidak selalu langsung cocok dengan istilah, tahapan, atau laporan setiap bengkel.', 'Mulai dari modul yang tersedia dan petakan perubahan yang benar-benar dibutuhkan.', ['workflow dapat dibahas sesuai SOP', 'branding dan identitas bisnis dapat dikonsultasikan', 'integrasi mengikuti ruang lingkup teknis', 'pengembangan lebih terarah'], ['customization', 'workflow', 'roles', 'reports'], 'Bengkel dengan SOP khusus, kebutuhan branding, atau rencana integrasi.', ['source-code-aplikasi-bengkel', 'aplikasi-bengkel-custom', 'aplikasi-bengkel-white-label']),
            'aplikasi-bengkel-custom' => self::page('customization', 'Aplikasi Bengkel Custom untuk Workflow Otomotif', 'Aplikasi Bengkel Custom sesuai Kebutuhan Operasional', 'Sesuaikan aplikasi bengkel dengan istilah, status, form, dokumen, dan laporan yang digunakan tim Anda.', 'CUSTOM WORKFLOW', 'Perbedaan proses kerja membuat satu konfigurasi standar tidak selalu cukup.', 'Konsultasikan perubahan yang dibutuhkan agar customisasi tetap fokus pada dampak operasional.', ['penyesuaian workflow', 'branding dan domain dapat dibahas', 'modul diprioritaskan berdasarkan kebutuhan', 'scope perubahan dapat disepakati'], ['customization', 'workflow', 'roles', 'reports'], 'Bengkel dengan proses khusus atau kebutuhan operasional yang berkembang.', ['aplikasi-bengkel-bisa-custom', 'source-code-aplikasi-bengkel', 'harga-aplikasi-bengkel']),
            'aplikasi-bengkel-white-label' => self::page('customization', 'Aplikasi Bengkel White Label | Branding dan Domain Sendiri', 'Aplikasi Bengkel White Label untuk Identitas Bisnis Anda', 'Gunakan aplikasi dengan identitas brand, logo, domain, dan alur yang dapat dikonsultasikan untuk kebutuhan bisnis Anda.', 'WHITE LABEL', 'Perusahaan software atau jaringan usaha mungkin membutuhkan produk dengan identitas sendiri.', 'Bahas branding, domain deployment, dan workflow sesuai paket serta lisensi yang disepakati.', ['brand dan logo dapat dikonsultasikan', 'domain deployment dapat dibahas', 'workflow dapat disesuaikan', 'cocok untuk jaringan usaha atau produk internal'], ['customization', 'deployment', 'workflow', 'roles'], 'Agency, perusahaan IT, dan jaringan bengkel yang ingin memakai identitas sendiri.', ['source-code-bengkel-white-label', 'source-code-aplikasi-bengkel', 'harga-aplikasi-bengkel']),
            'source-code-bengkel-white-label' => self::page('customization', 'Source Code Bengkel White Label untuk Produk Anda', 'Source Code Bengkel White Label dengan Identitas Sendiri', 'Dapatkan basis source code aplikasi bengkel untuk dibahas penggunaannya dengan brand, domain, dan workflow Anda sendiri.', 'SOURCE CODE WHITE LABEL', 'Membangun produk software beridentitas sendiri memerlukan fondasi teknis dan ruang lingkup branding yang jelas.', 'Gunakan source code sesuai lisensi dan sepakati kebutuhan white-label secara spesifik.', ['basis software bengkel berbasis web', 'branding dan domain dapat dikonsultasikan', 'custom workflow untuk kebutuhan produk', 'ruang lingkup lisensi dibahas sejak awal'], ['source_code', 'customization', 'deployment', 'workflow'], 'Agency dan penyedia solusi yang ingin menawarkan software dengan brand sendiri.', ['aplikasi-bengkel-white-label', 'source-code-aplikasi-bengkel', 'harga-source-code-aplikasi-bengkel']),
            'aplikasi-bengkel-laravel' => self::page('technology', 'Aplikasi Bengkel Laravel Berbasis Web | Bisa Dikembangkan', 'Aplikasi Bengkel Laravel untuk Fondasi Pengembangan', 'Aplikasi bengkel berbasis Laravel, PHP, dan MySQL untuk kebutuhan operasional dan pengembangan software internal.', 'LARAVEL WEB BASED', 'Tim teknis perlu memahami stack sebelum memutuskan apakah solusi dapat dirawat dan dikembangkan.', 'Stack web yang familiar membantu tim membahas deployment, customisasi, dan integrasi secara konkret.', ['Laravel dan PHP', 'MySQL untuk data aplikasi', 'web based untuk akses browser', 'source code sesuai paket dan lisensi'], ['source_code', 'deployment', 'customization', 'workflow'], 'Developer, agency, dan tim IT yang memilih stack Laravel.', ['source-code-aplikasi-bengkel-laravel', 'source-code-aplikasi-bengkel', 'aplikasi-bengkel-web-based']),
            'source-code-aplikasi-bengkel-laravel' => self::page('technology', 'Source Code Aplikasi Bengkel Laravel | Mulai Rp 7 Juta', 'Source Code Aplikasi Bengkel Laravel', 'Pelajari source code aplikasi bengkel berbasis Laravel, PHP, dan MySQL dengan harga mulai Rp 7.000.000.', 'STACK UNTUK DEVELOPER', 'Tim teknis membutuhkan fondasi bisnis yang lebih konkret daripada template halaman kosong.', 'Mulai dari modul operasional yang tersedia lalu konsultasikan scope source code dan lisensi.', ['Laravel untuk backend aplikasi', 'PHP sebagai runtime utama', 'MySQL sebagai database', 'web based dan dapat dibahas untuk deployment sendiri'], ['source_code', 'deployment', 'customization'], 'Developer dan perusahaan IT yang membutuhkan aplikasi Laravel sebagai fondasi.', ['aplikasi-bengkel-laravel', 'source-code-bengkel-php', 'source-code-bengkel-mysql']),
            'source-code-bengkel-php' => self::page('technology', 'Source Code Bengkel PHP untuk Pengembangan Aplikasi', 'Source Code Aplikasi Bengkel Berbasis PHP', 'Source code aplikasi bengkel dengan stack PHP dan Laravel untuk tim yang ingin melanjutkan pengembangan software berbasis web.', 'PHP APPLICATION', 'Tim PHP membutuhkan fondasi bisnis yang lebih konkret daripada template halaman kosong.', 'Mulai dari modul operasional yang terverifikasi lalu kembangkan kebutuhan khusus.', ['PHP dan Laravel', 'data operasional bengkel', 'workflow siap ditinjau', 'scope lisensi dikonsultasikan'], ['source_code', 'workflow', 'customization'], 'Developer PHP, agency, dan tim internal.', ['source-code-aplikasi-bengkel-laravel', 'aplikasi-bengkel-laravel', 'source-code-aplikasi-bengkel']),
            'source-code-bengkel-mysql' => self::page('technology', 'Source Code Bengkel MySQL untuk Manajemen Data Workshop', 'Source Code Aplikasi Bengkel dengan Database MySQL', 'Pelajari basis aplikasi bengkel yang memakai MySQL untuk data customer, kendaraan, pekerjaan, parts, invoice, dan laporan.', 'DATA WORKSHOP', 'Data operasional yang saling terkait membutuhkan struktur penyimpanan yang dapat dirawat dan dikembangkan.', 'Bahas kebutuhan deployment dan integrasi data berdasarkan lingkungan teknis Anda.', ['MySQL untuk data aplikasi', 'domain operasional bengkel tersedia', 'web based dan mudah diakses browser', 'pengembangan lanjutan dapat dibahas'], ['source_code', 'deployment', 'inventory', 'history'], 'Developer dan tim IT yang memakai ekosistem PHP-MySQL.', ['source-code-aplikasi-bengkel-laravel', 'source-code-bengkel-php', 'source-code-aplikasi-bengkel']),
            'aplikasi-bengkel-web-based' => self::page('technology', 'Aplikasi Bengkel Web Based untuk Akses Tim', 'Aplikasi Bengkel Berbasis Web', 'Akses aplikasi bengkel melalui browser untuk mengelola customer, kendaraan, pekerjaan, parts, QC, invoice, dan laporan.', 'WEB BASED', 'Aplikasi yang hanya tersedia di satu perangkat dapat menyulitkan koordinasi antar meja dan area kerja.', 'Model web based membuat pembahasan akses, deployment, dan penggunaan multi-user lebih sederhana.', ['akses melalui browser', 'mendukung alur multi-user', 'deployment dapat dikonsultasikan', 'cocok untuk desktop dan tablet'], ['source_code', 'roles', 'workflow', 'reports'], 'Workshop dengan beberapa peran pengguna dan kebutuhan akses terpusat.', ['aplikasi-bengkel-online', 'aplikasi-bengkel-multi-user', 'source-code-aplikasi-bengkel']),
            'aplikasi-bengkel-online' => self::page('technology', 'Aplikasi Bengkel Online Berbasis Browser', 'Aplikasi Bengkel Online untuk Tim yang Terhubung', 'Kelola proses bengkel dari browser dengan sistem online yang menyatukan data customer, pekerjaan, inventory, QC, invoice, dan laporan.', 'AKSES ONLINE', 'Koordinasi sulit jika informasi pekerjaan hanya tersimpan di satu komputer atau lembar terpisah.', 'Aplikasi online membantu peran yang berwenang bekerja dari titik kerja masing-masing.', ['web based', 'multi-user dengan role', 'alur pekerjaan terhubung', 'dokumen customer-facing siap digunakan'], ['roles', 'workflow', 'inventory', 'qc', 'invoice'], 'Bengkel yang membutuhkan akses aplikasi terpusat.', ['aplikasi-bengkel-web-based', 'aplikasi-bengkel-multi-user', 'source-code-aplikasi-bengkel']),
            'aplikasi-bengkel-mobil' => self::page('segment', 'Aplikasi Bengkel Mobil Berbasis Web | Bisa Custom', 'Aplikasi Bengkel Mobil untuk Alur Service yang Terstruktur', 'Kelola customer, kendaraan, keluhan, temuan, estimasi, pekerjaan mekanik, sparepart, QC, invoice, dan histori service mobil.', 'UNTUK BENGKEL MOBIL', 'Service mobil sering melibatkan inspeksi, rekomendasi pekerjaan, dan kombinasi parts serta jasa.', 'Simpan konteks kendaraan dan rencana pekerjaan dari check-in sampai kendaraan siap diserahkan.', ['data kendaraan dan histori lebih mudah dicari', 'estimasi parts dan jasa', 'job card dan QC', 'laporan untuk pemilik usaha'], ['customers', 'vehicles', 'findings', 'estimates', 'jobcards', 'qc', 'history'], 'Bengkel mobil dan workshop general repair kendaraan roda empat.', ['aplikasi-bengkel-motor', 'aplikasi-bengkel-estimasi', 'source-code-aplikasi-bengkel']),
            'aplikasi-bengkel-motor' => self::page('segment', 'Aplikasi Bengkel Motor untuk Service dan Sparepart', 'Aplikasi Bengkel Motor untuk Operasional Harian', 'Bantu bengkel motor mengatur customer, kendaraan, temuan, estimasi jasa dan parts, pekerjaan teknisi, QC, invoice, serta riwayat service.', 'UNTUK BENGKEL MOTOR', 'Volume kendaraan roda dua dapat membuat pencatatan cepat dan histori service mudah tercecer.', 'Gunakan alur ringkas yang tetap menyimpan informasi kendaraan dan pekerjaan.', ['penerimaan kendaraan lebih teratur', 'jasa dan parts tersusun', 'histori service customer', 'mendukung workflow teknisi'], ['customers', 'vehicles', 'estimates', 'work', 'parts', 'qc', 'history'], 'Bengkel motor dan workshop roda dua.', ['aplikasi-bengkel-mobil', 'aplikasi-bengkel-sparepart', 'source-code-aplikasi-bengkel']),
            'aplikasi-workshop-otomotif' => self::page('segment', 'Aplikasi Workshop Otomotif untuk Mobil dan Motor', 'Aplikasi Workshop Otomotif Berbasis Web', 'Aplikasi untuk workshop otomotif yang ingin mengelola kendaraan, pekerjaan teknisi, sparepart, QC, dokumen, dan laporan.', 'OTOMOTIF MOBIL & MOTOR', 'Workshop otomotif membutuhkan sistem yang mampu mengikuti variasi kendaraan dan pekerjaan.', 'Bangun alur terstruktur dari customer datang sampai kendaraan selesai.', ['mendukung mobil dan motor', 'data kendaraan terpusat', 'parts dan jasa dalam estimasi', 'QC sebelum selesai'], ['customers', 'vehicles', 'estimates', 'jobcards', 'inventory', 'qc'], 'Workshop otomotif dengan layanan yang beragam.', ['aplikasi-bengkel-mobil', 'aplikasi-bengkel-motor', 'source-code-aplikasi-bengkel']),
        ];

        $pages += [
            'source-code-bengkel' => self::page('source_code', 'Source Code Bengkel untuk Sistem Manajemen Workshop', 'Source Code Bengkel untuk Dikembangkan Sesuai Kebutuhan', 'Dapatkan basis software manajemen bengkel untuk dikembangkan dengan workflow, branding, dan deployment yang sesuai kebutuhan.', 'SOURCE CODE BENGKEL', 'Membangun seluruh domain workshop dari awal membutuhkan pemodelan proses dan dokumen yang panjang.', 'Mulai dari fondasi aplikasi yang sudah memiliki customer, service, parts, QC, invoice, dan laporan.', ['fondasi domain workshop', 'ruang pengembangan custom', 'web based dan dapat dibahas untuk deployment', 'source code mengikuti paket dan lisensi'], ['source_code', 'workflow', 'customization', 'deployment'], 'Developer, agency, dan pemilik bisnis yang membutuhkan fondasi software bengkel.', ['source-code-aplikasi-bengkel', 'aplikasi-bengkel-laravel', 'harga-source-code-aplikasi-bengkel']),
            'source-code-bengkel-laravel' => self::page('technology', 'Source Code Bengkel Laravel untuk Aplikasi Workshop', 'Source Code Bengkel Berbasis Laravel', 'Bangun atau kembangkan aplikasi workshop dengan source code berbasis Laravel, PHP, dan MySQL.', 'LARAVEL WORKSHOP', 'Tim pengembang membutuhkan kode yang dapat dipahami dan konteks bisnis yang tidak kosong.', 'Gunakan fondasi modul workshop untuk mempercepat pembahasan teknis dan kebutuhan custom.', ['Laravel dan PHP', 'MySQL', 'domain workflow workshop', 'customisasi dan deployment dapat dibahas'], ['source_code', 'workflow', 'customization', 'deployment'], 'Developer dan tim IT yang memilih ekosistem Laravel.', ['aplikasi-bengkel-laravel', 'source-code-aplikasi-bengkel-laravel', 'source-code-aplikasi-bengkel']),
            'source-code-aplikasi-workshop' => self::page('source_code', 'Source Code Aplikasi Workshop Otomotif | Bisa Custom', 'Source Code Aplikasi Workshop Otomotif', 'Dapatkan fondasi aplikasi workshop otomotif untuk customer, kendaraan, pekerjaan mekanik, parts, QC, invoice, dan laporan.', 'WORKSHOP SOURCE CODE', 'Workshop otomotif memiliki proses khusus yang perlu dijelaskan sebelum pengembangan dilanjutkan.', 'Gunakan modul domain yang tersedia dan bahas penyesuaian sesuai paket serta lisensi.', ['fitur workshop nyata', 'customer dan kendaraan', 'parts dan pekerjaan', 'opsi custom workflow'], ['source_code', 'customers', 'vehicles', 'work', 'inventory', 'qc'], 'Agency, developer, dan jaringan workshop otomotif.', ['source-code-aplikasi-bengkel', 'aplikasi-workshop-otomotif', 'aplikasi-bengkel-custom']),
            'source-code-erp-bengkel' => self::page('source_code', 'Source Code ERP Bengkel untuk Operasional Terpadu', 'Source Code ERP Bengkel', 'Mulai dari source code ERP bengkel dengan alur customer, service, inventory, QC, invoice, dan laporan yang dapat dikembangkan.', 'ERP SOURCE CODE', 'ERP bengkel memerlukan hubungan data antar proses, bukan hanya daftar menu.', 'Tinjau alur yang tersedia lalu susun roadmap pengembangan sesuai prioritas usaha.', ['alur operasional terhubung', 'modul inventory dan service', 'role management', 'source code sesuai lisensi'], ['source_code', 'workflow', 'inventory', 'roles', 'reports'], 'Perusahaan yang mengembangkan atau mengintegrasikan ERP workshop.', ['erp-bengkel', 'source-code-aplikasi-bengkel', 'aplikasi-bengkel-multi-cabang']),
            'source-code-software-bengkel' => self::page('source_code', 'Source Code Software Bengkel untuk Produk Digital', 'Source Code Software Bengkel', 'Gunakan source code software bengkel sebagai basis untuk produk digital, implementasi internal, atau pengembangan customer.', 'SOFTWARE SOURCE CODE', 'Produk B2B memerlukan fondasi proses yang dapat dipresentasikan kepada calon pengguna.', 'Tunjukkan workflow nyata dan bahas branding, deployment, serta customisasi secara terukur.', ['workflow siap ditinjau', 'fitur customer dan service', 'opsi branding', 'scope lisensi dikonsultasikan'], ['source_code', 'workflow', 'customization', 'deployment'], 'Vendor software dan agency yang melayani bisnis bengkel.', ['source-code-aplikasi-bengkel', 'source-code-bengkel-white-label', 'jual-software-bengkel']),
            'beli-source-code-aplikasi-bengkel' => self::page('source_code', 'Beli Source Code Aplikasi Bengkel | Mulai Rp 7 Juta', 'Beli Source Code Aplikasi Bengkel', 'Beli source code aplikasi bengkel untuk dikembangkan atau diimplementasikan sesuai paket dan lisensi yang disepakati.', 'BELI SOURCE CODE', 'Pembeli perlu memahami fitur, stack, dan scope lisensi sebelum mengambil keputusan.', 'Gunakan halaman fitur dan konsultasi langsung untuk memastikan kebutuhan Anda terpetakan.', ['harga mulai Rp 7.000.000', 'Laravel, PHP, dan MySQL', 'fitur operasional workshop', 'customisasi dapat dibahas'], ['source_code', 'workflow', 'customization', 'deployment'], 'Pemilik bisnis, developer, dan agency.', ['source-code-aplikasi-bengkel', 'harga-source-code-aplikasi-bengkel', 'aplikasi-bengkel-laravel']),
            'jual-source-code-aplikasi-bengkel' => self::page('source_code', 'Jual Source Code Aplikasi Bengkel | Solusi White Label', 'Jual Source Code Aplikasi Bengkel', 'Tawarkan solusi workshop dengan source code aplikasi bengkel, opsi custom workflow, branding, dan deployment sesuai kesepakatan.', 'UNTUK VENDOR SOFTWARE', 'Penyedia solusi membutuhkan produk domain-specific yang dapat dijelaskan dan dikembangkan.', 'Mulai dari fondasi software bengkel dan bahas kebutuhan komersial secara terbuka.', ['fitur workshop siap didemokan', 'source code sesuai lisensi', 'opsi white-label', 'custom workflow'], ['source_code', 'customization', 'workflow', 'deployment'], 'Agency, vendor, dan reseller software.', ['jual-software-bengkel', 'source-code-bengkel-white-label', 'source-code-aplikasi-bengkel']),
            'beli-software-bengkel' => self::page('use_case', 'Beli Software Bengkel Berbasis Web | Mulai Rp 7 Juta', 'Beli Software Bengkel untuk Digitalisasi Operasional', 'Mulai dari software bengkel berbasis web dengan harga Rp 7.000.000 dan konsultasikan kebutuhan implementasi Anda.', 'SIAP KONSULTASI', 'Pemilik usaha perlu menghubungkan kebutuhan operasional dengan fitur sebelum memilih solusi.', 'Gunakan alur fitur dan CTA halaman ini untuk meminta demo atau penawaran yang relevan.', ['harga awal jelas', 'fitur customer sampai laporan', 'web based untuk tim', 'customisasi dapat dibahas'], ['workflow', 'customers', 'inventory', 'invoice', 'reports'], 'Pemilik bengkel yang siap beralih dari pencatatan manual.', ['harga-software-bengkel', 'source-code-aplikasi-bengkel', 'aplikasi-bengkel']),
            'jual-software-bengkel' => self::page('use_case', 'Jual Software Bengkel Custom & White Label', 'Jual Software Bengkel dengan Pilihan Customisasi', 'Untuk penyedia solusi, aplikasi bengkel ini dapat menjadi basis penawaran software, custom workflow, dan white-label sesuai kesepakatan.', 'UNTUK PENYEDIA SOLUSI', 'Produk software B2B membutuhkan alur yang dapat dijelaskan dan disesuaikan.', 'Tinjau modul yang tersedia lalu diskusikan branding, deployment, dan lisensi.', ['modul operasional dapat didemokan', 'white-label dapat dikonsultasikan', 'custom workflow', 'source code sesuai lisensi'], ['source_code', 'customization', 'deployment', 'workflow'], 'Agency dan vendor software yang melayani bengkel.', ['jual-source-code-aplikasi-bengkel', 'aplikasi-bengkel-white-label', 'source-code-bengkel-white-label']),
            'beli-source-code-bengkel' => self::page('source_code', 'Beli Source Code Bengkel | Laravel, PHP & MySQL', 'Beli Source Code Bengkel untuk Dikembangkan', 'Beli source code aplikasi bengkel dengan stack Laravel, PHP, dan MySQL sesuai paket serta lisensi yang disepakati.', 'SOURCE CODE SIAP DIKEMBANGKAN', 'Tim teknis membutuhkan kendali lebih besar atas deployment, customisasi, dan integrasi.', 'Mulai dari fondasi software bengkel lalu sesuaikan rencana pengembangan.', ['source code sesuai lisensi', 'Laravel, PHP, dan MySQL', 'dapat dibahas untuk server sendiri', 'cocok untuk pengembangan bertahap'], ['source_code', 'deployment', 'customization'], 'Developer, agency, dan perusahaan dengan tim teknis.', ['source-code-aplikasi-bengkel', 'source-code-aplikasi-bengkel-laravel', 'harga-source-code-aplikasi-bengkel']),
            'harga-source-code-bengkel' => self::page('price', 'Harga Source Code Bengkel | Mulai Rp 7 Juta', 'Harga Source Code Bengkel', 'Informasi harga source code bengkel mulai Rp 7.000.000 dengan ruang lingkup lisensi, customisasi, dan deployment yang dapat dibahas.', 'HARGA SOURCE CODE', 'Source code dan pekerjaan implementasi tambahan perlu dibedakan sejak awal.', 'Konsultasikan kebutuhan agar penawaran mencerminkan scope yang dibutuhkan.', ['harga mulai Rp 7.000.000', 'scope lisensi jelas', 'customisasi dapat dibahas', 'CTA langsung ke tim penjualan'], ['source_code', 'customization', 'deployment'], 'Pembeli source code dan penyedia solusi workshop.', ['harga-aplikasi-bengkel', 'source-code-aplikasi-bengkel', 'aplikasi-bengkel-white-label']),
            'source-code-aplikasi-bengkel-bisa-custom' => self::page('customization', 'Source Code Aplikasi Bengkel Bisa Custom | Laravel Web Based', 'Source Code Aplikasi Bengkel untuk Pengembangan Custom', 'Source code aplikasi bengkel membantu tim memulai dari fondasi customer, pekerjaan, parts, QC, invoice, dan laporan.', 'DASAR PENGEMBANGAN', 'Membangun aplikasi bengkel dari nol membutuhkan waktu untuk memodelkan alur dan dokumen operasional.', 'Gunakan source code sesuai paket dan lisensi sebagai dasar pengembangan lanjutan.', ['fondasi backend dan frontend sesuai paket', 'workflow dapat dipetakan', 'deployment di server sendiri dapat dibahas', 'integrasi lanjutan lebih terarah'], ['source_code', 'customization', 'deployment', 'workflow'], 'Developer atau tim IT yang ingin mempercepat pengembangan.', ['source-code-aplikasi-bengkel-laravel', 'aplikasi-bengkel-custom', 'harga-source-code-aplikasi-bengkel']),
            'software-bengkel-custom' => self::page('customization', 'Software Bengkel Custom untuk Operasional Spesifik', 'Software Bengkel Custom Tanpa Mengulang dari Nol', 'Bangun software bengkel yang lebih dekat dengan SOP bisnis melalui fondasi modul yang tersedia dan pembahasan kebutuhan custom.', 'CUSTOM SOFTWARE', 'Perubahan alur penerimaan, mekanik, atau laporan dapat berdampak besar pada pekerjaan harian.', 'Petakan proses penting dan kembangkan perubahan yang memberi nilai paling nyata.', ['custom workflow', 'akses peran dapat ditinjau', 'integrasi dibahas secara teknis', 'implementasi dapat bertahap'], ['customization', 'workflow', 'roles', 'reports'], 'Workshop atau perusahaan yang membutuhkan penyesuaian proses.', ['aplikasi-bengkel-custom', 'aplikasi-bengkel-multi-user', 'source-code-aplikasi-bengkel']),
            'aplikasi-general-repair' => self::page('segment', 'Aplikasi Bengkel General Repair untuk Banyak Jenis Pekerjaan', 'Aplikasi Bengkel untuk General Repair', 'Dukung general repair dengan pencatatan customer, kendaraan, temuan, estimasi parts dan jasa, tugas mekanik, QC, invoice, serta histori.', 'GENERAL REPAIR', 'General repair menangani jenis pekerjaan beragam sehingga konteks temuan dan pekerjaan perlu terdokumentasi.', 'Gunakan temuan, estimasi, dan work order sebagai penghubung diagnosis dan pekerjaan.', ['cocok untuk pekerjaan beragam', 'temuan dan rekomendasi tersimpan', 'estimasi parts dan jasa', 'histori membantu kunjungan berikutnya'], ['findings', 'estimates', 'work', 'parts', 'qc', 'history'], 'Bengkel general repair mobil maupun motor.', ['aplikasi-workshop-otomotif', 'aplikasi-bengkel-estimasi', 'source-code-aplikasi-bengkel']),
            'aplikasi-tune-up' => self::page('segment', 'Aplikasi Bengkel Tune Up untuk Temuan dan Pekerjaan', 'Aplikasi Bengkel untuk Pekerjaan Tune Up', 'Kelola temuan tune up, rekomendasi pekerjaan, estimasi parts dan jasa, tugas mekanik, QC, serta histori customer.', 'LAYANAN TUNE UP', 'Pekerjaan tune up sering membutuhkan rekomendasi tambahan setelah pemeriksaan kendaraan.', 'Hubungkan temuan dengan rencana pekerjaan dan informasi harga sebelum customer mengambil keputusan.', ['temuan dan rekomendasi', 'estimasi customer', 'work task mekanik', 'QC setelah pekerjaan'], ['findings', 'estimates', 'work', 'qc', 'history'], 'Bengkel yang melayani tune up dan preventive maintenance.', ['aplikasi-bengkel-estimasi', 'aplikasi-bengkel-job-card', 'source-code-aplikasi-bengkel']),
            'aplikasi-sparepart-bengkel' => self::page('segment', 'Aplikasi Sparepart Bengkel untuk Stok dan Pemakaian', 'Aplikasi Bengkel dengan Pengelolaan Sparepart', 'Kelola master product, stok, pergerakan, penggunaan dalam pekerjaan, pembelian, dan laporan sparepart.', 'SPAREPART BENGKEL', 'Stok sulit dikendalikan jika pembelian, pemakaian, dan penyesuaian tidak tercatat dalam satu alur.', 'Hubungkan inventory dengan pekerjaan dan laporan agar keputusan pengadaan lebih terukur.', ['master product dan unit', 'histori pergerakan stok', 'pemakaian parts dalam pekerjaan', 'laporan stok dan pembelian'], ['parts', 'inventory', 'work', 'reports'], 'Bengkel yang memiliki banyak jenis sparepart atau gudang.', ['aplikasi-bengkel-inventory', 'aplikasi-bengkel-estimasi', 'source-code-aplikasi-bengkel']),
            'aplikasi-service-mobil' => self::page('segment', 'Aplikasi Service Mobil untuk Customer dan Riwayat Kendaraan', 'Aplikasi Service Mobil dengan Histori yang Terhubung', 'Atur penerimaan, keluhan, temuan, estimasi, pengerjaan, QC, invoice, dan riwayat service mobil secara terstruktur.', 'SERVICE MOBIL', 'Customer perlu mendapat informasi jelas, sementara tim perlu melihat histori dan pekerjaan berjalan.', 'Gunakan satu alur data kendaraan dari check-in sampai histori service.', ['data customer dan kendaraan', 'temuan menuju estimasi', 'progress pekerjaan', 'histori service'], ['customers', 'vehicles', 'checkin', 'findings', 'estimates', 'work', 'history'], 'Bengkel service mobil dan workshop multi-layanan.', ['aplikasi-bengkel-mobil', 'aplikasi-bengkel-riwayat-servis', 'source-code-aplikasi-bengkel']),
            'aplikasi-service-motor' => self::page('segment', 'Aplikasi Service Motor untuk Customer dan Pekerjaan Mekanik', 'Aplikasi Service Motor untuk Alur yang Lebih Cepat', 'Buat alur service motor yang ringkas namun tetap mencatat customer, kendaraan, estimasi, pekerjaan, parts, QC, dan histori.', 'SERVICE MOTOR', 'Kecepatan penerimaan harus tetap diimbangi catatan pekerjaan yang dapat dilacak.', 'Sediakan data yang dibutuhkan mekanik dan customer tanpa pencatatan ganda.', ['check-in praktis', 'estimasi jasa dan parts', 'job task mekanik', 'histori kendaraan'], ['customers', 'vehicles', 'estimates', 'work', 'parts', 'history'], 'Bengkel service motor dan jaringan roda dua.', ['aplikasi-bengkel-motor', 'aplikasi-bengkel-sparepart', 'source-code-aplikasi-bengkel']),
            'jual-source-code-bengkel' => self::page('source_code', 'Jual Source Code Bengkel Laravel | Aplikasi Siap Dikembangkan', 'Jual Source Code Aplikasi Bengkel', 'Dapatkan informasi source code aplikasi bengkel berbasis web untuk dikembangkan sesuai kebutuhan operasional dan lisensi yang disepakati.', 'SOURCE CODE BENGKEL', 'Membangun sistem bengkel dari nol membutuhkan waktu untuk memodelkan customer, pekerjaan, parts, dokumen, dan laporan.', 'Mulai dari fondasi aplikasi yang sudah memiliki alur workshop lalu bahas customisasi serta deployment.', ['source code sesuai paket dan lisensi', 'modul operasional dapat ditinjau', 'customisasi dan deployment dapat dikonsultasikan', 'cocok untuk developer atau pemilik bengkel'], ['source_code', 'workflow', 'customization', 'deployment'], 'Developer, agency, dan pemilik bengkel yang mencari source code.', ['source-code-aplikasi-bengkel', 'source-code-aplikasi-bengkel-laravel', 'harga-source-code-aplikasi-bengkel']),
            'source-code-aplikasi-bengkel-harga-7-juta' => self::page('price', 'Source Code Aplikasi Bengkel Harga 7 Juta | Mulai Rp 7.000.000', 'Source Code Aplikasi Bengkel Mulai Rp 7.000.000', 'Harga awal source code aplikasi bengkel mulai Rp 7.000.000. Ruang lingkup lisensi, customisasi, integrasi, dan deployment dibahas sesuai kebutuhan.', 'SOURCE CODE RP 7 JUTA', 'Pembeli perlu memahami apa yang termasuk dalam paket sebelum memutuskan pembelian source code.', 'Gunakan harga mulai sebagai titik awal konsultasi dan susun scope yang jelas.', ['harga mulai Rp 7.000.000', 'source code sesuai paket dan lisensi', 'customisasi dapat dibahas', 'scope deployment dapat disepakati'], ['source_code', 'customization', 'deployment', 'workflow'], 'Pemilik bengkel, developer, dan agency yang mencari source code pada kisaran Rp7 juta.', ['harga-aplikasi-bengkel', 'source-code-aplikasi-bengkel', 'source-code-aplikasi-bengkel-laravel']),
            'aplikasi-bengkel-murah' => self::page('price', 'Aplikasi Bengkel Murah Berbasis Web | Mulai Rp 7 Juta', 'Aplikasi Bengkel dengan Investasi Awal Terukur', 'Cari aplikasi bengkel yang memberi fondasi operasional dan source code dengan harga mulai Rp 7.000.000, tanpa mengabaikan kebutuhan customisasi.', 'INVESTASI TERUKUR', 'Harga murah tidak banyak membantu jika workflow penting tetap harus dicatat di tempat lain.', 'Bandingkan cakupan modul dan kebutuhan implementasi sebelum menentukan pilihan software.', ['harga mulai Rp 7.000.000', 'fitur workflow inti tersedia', 'source code sesuai paket dan lisensi', 'customisasi dibahas berdasarkan kebutuhan'], ['source_code', 'workflow', 'estimates', 'inventory'], 'Bengkel yang mencari software dengan investasi awal terukur.', ['harga-aplikasi-bengkel', 'aplikasi-bengkel', 'source-code-aplikasi-bengkel']),
            'software-bengkel-murah' => self::page('price', 'Software Bengkel Murah untuk Operasional Terstruktur', 'Software Bengkel dengan Harga Mulai Rp 7.000.000', 'Software bengkel berbasis web dengan harga awal Rp 7.000.000 untuk membantu menghubungkan customer, pekerjaan, sparepart, QC, invoice, dan laporan.', 'SOFTWARE BENGKEL', 'Biaya software perlu dilihat bersama manfaat workflow dan kemampuan pengembangan yang dibutuhkan.', 'Mulai dengan kebutuhan utama, lalu konsultasikan scope implementasi agar penawaran tetap relevan.', ['harga awal transparan', 'workflow customer dan pekerjaan', 'inventory dan dokumen terhubung', 'opsi customisasi dapat dibahas'], ['workflow', 'source_code', 'inventory', 'invoice'], 'Pemilik workshop yang membandingkan software bengkel berdasarkan biaya dan cakupan.', ['harga-software-bengkel', 'software-bengkel', 'source-code-aplikasi-bengkel']),
        ];

        $features = [
            'inventory' => ['Aplikasi Bengkel dengan Inventory Sparepart | Full Source Code', 'Aplikasi Bengkel dengan Inventory Sparepart', 'Kelola master product, stok, pergerakan, dan pemakaian sparepart agar keputusan pengadaan tidak lagi bergantung pada catatan terpisah.', 'STOK LEBIH TERKONTROL', 'Stok yang tidak sinkron membuat tim ragu apakah parts tersedia dan kapan harus melakukan pengadaan.', 'Catat product dan pergerakannya dalam alur inventory yang terhubung dengan operasional bengkel.', ['stok sparepart lebih terkontrol', 'histori pergerakan stok', 'pemakaian parts dalam pekerjaan', 'laporan stok untuk evaluasi'], ['inventory', 'parts', 'work', 'reports'], ['aplikasi-bengkel-sparepart', 'aplikasi-bengkel-estimasi', 'source-code-aplikasi-bengkel']],
            'sparepart' => ['Aplikasi Bengkel Sparepart untuk Stok dan Pemakaian', 'Aplikasi Bengkel untuk Mengelola Sparepart', 'Susun data sparepart, harga jual, ketersediaan, pemakaian, dan histori secara mudah ditelusuri.', 'MASTER PARTS', 'Parts yang dicatat manual sulit ditelusuri dari pembelian sampai pemakaian.', 'Gunakan inventory dan item pekerjaan untuk menjaga konteks sparepart.', ['master product lebih rapi', 'informasi ketersediaan', 'pemakaian dapat ditelusuri', 'mendukung estimasi customer'], ['parts', 'inventory', 'estimates', 'work'], ['aplikasi-bengkel-inventory', 'aplikasi-bengkel-estimasi', 'source-code-aplikasi-bengkel']],
            'estimasi' => ['Aplikasi Bengkel dengan Estimasi Customer | Print PDF WhatsApp', 'Aplikasi Bengkel dengan Estimasi Servis Customer', 'Buat informasi harga parts dan jasa sebelum pekerjaan dilakukan, lalu tampilkan total, print, PDF, WhatsApp, approval, dan revisi sesuai alur aplikasi.', 'ESTIMASI PROFESIONAL', 'Estimasi manual sulit diedit, dihitung ulang, dan dibagikan dengan format konsisten.', 'Susun sparepart, jasa, qty, harga, diskon, dan total sebagai informasi customer sebelum pekerjaan dimulai.', ['tambah sparepart dan jasa', 'qty, harga, diskon, dan total', 'print dan PDF customer-facing', 'kirim WhatsApp dan approval customer', 'revisi untuk perubahan scope'], ['estimates', 'parts', 'whatsapp', 'approval', 'workflow'], ['source-code-aplikasi-bengkel', 'harga-aplikasi-bengkel', 'aplikasi-bengkel-whatsapp']],
            'invoice' => ['Aplikasi Bengkel dengan Invoice dari Pekerjaan', 'Aplikasi Bengkel dengan Invoice yang Terhubung ke Pekerjaan', 'Buat invoice berdasarkan pekerjaan yang sudah diproses dalam alur bengkel, dengan item, total, pembayaran, PDF, dan dokumen customer.', 'INVOICE TERINTEGRASI', 'Invoice lebih sulit dikendalikan jika dibuat terpisah dari pekerjaan dan item yang disepakati.', 'Hubungkan hasil pekerjaan dan item komersial dengan proses invoice yang sudah ada.', ['item pekerjaan lebih mudah ditelusuri', 'dokumen invoice dan PDF', 'pembayaran pada domain invoice', 'batas estimate dan invoice tetap jelas'], ['invoice', 'work', 'payments', 'history'], ['aplikasi-bengkel-estimasi', 'aplikasi-bengkel-laporan', 'source-code-aplikasi-bengkel']],
            'whatsapp' => ['Aplikasi Bengkel dengan Estimasi WhatsApp untuk Customer', 'Kirim Informasi Estimasi Bengkel melalui WhatsApp', 'Bagikan informasi estimasi, nomor dokumen, kendaraan, total, masa berlaku, dan tautan publik melalui WhatsApp customer.', 'KOMUNIKASI CUSTOMER', 'Customer membutuhkan informasi harga yang mudah dibuka dari ponsel.', 'Gunakan dokumen estimasi dan tautan publik agar customer dapat membaca informasi dari perangkatnya.', ['pesan berisi ringkasan estimasi', 'tautan publik customer', 'nomor estimasi dan kendaraan', 'CTA WhatsApp untuk komunikasi'], ['whatsapp', 'estimates', 'customers'], ['aplikasi-bengkel-estimasi', 'source-code-aplikasi-bengkel', 'harga-aplikasi-bengkel']],
            'qc' => ['Aplikasi Bengkel dengan Quality Control Setelah Pekerjaan', 'Aplikasi Bengkel dengan QC untuk Menjaga Kualitas Pekerjaan', 'Bantu tim melakukan quality control setelah pekerjaan mekanik selesai sebelum kendaraan masuk tahap akhir.', 'QUALITY CONTROL', 'Pekerjaan yang selesai perlu diperiksa dengan langkah terlihat sebelum customer menerima kendaraan.', 'Sediakan tahapan QC sebagai bagian dari alur workshop, bukan catatan terpisah.', ['status QC lebih jelas', 'handover mekanik ke pemeriksa', 'mendukung bukti pekerjaan', 'alur selesai lebih tertib'], ['qc', 'work', 'jobcards', 'history'], ['aplikasi-bengkel-job-card', 'aplikasi-bengkel', 'source-code-aplikasi-bengkel']],
            'job-card' => ['Aplikasi Bengkel dengan Job Card Mekanik', 'Aplikasi Bengkel dengan Job Card untuk Pekerjaan Mekanik', 'Atur rencana dan tugas pekerjaan mekanik dengan job card yang terhubung ke service, item, temuan, dan QC.', 'JOB CARD DIGITAL', 'Mekanik membutuhkan instruksi dan status pekerjaan yang lebih jelas daripada pesan lisan.', 'Job card memberi konteks pekerjaan dan membantu koordinasi sampai QC.', ['tugas mekanik lebih terarah', 'status pekerjaan mudah dipantau', 'item dan temuan tetap terkait', 'mendukung proses QC'], ['jobcards', 'work', 'findings', 'qc'], ['aplikasi-bengkel-qc', 'aplikasi-bengkel-estimasi', 'source-code-aplikasi-bengkel']],
            'multi-user' => ['Aplikasi Bengkel Multi User dengan Akses Sesuai Peran', 'Aplikasi Bengkel Multi User untuk Tim Operasional', 'Gunakan aplikasi bengkel bersama tim penerimaan, mekanik, QC, kasir, dan pemilik dengan akses sesuai kebutuhan peran.', 'MULTI USER', 'Aplikasi bersama tanpa pembagian akses dapat membuat informasi dan tindakan penting sulit dikendalikan.', 'Gunakan role dan permission yang tersedia untuk mengatur akses.', ['akses peran lebih terarah', 'mendukung handover antar tim', 'aktivitas tersimpan dalam sistem', 'cocok untuk operasional harian'], ['users', 'roles', 'workflow', 'reports'], ['aplikasi-bengkel-role-management', 'aplikasi-bengkel', 'source-code-aplikasi-bengkel']],
            'role-management' => ['Aplikasi Bengkel dengan Role Management dan Permission', 'Role Management untuk Mengatur Akses Pengguna Bengkel', 'Atur peran pengguna dan permission agar setiap bagian melihat serta menjalankan fungsi sesuai tanggung jawabnya.', 'AKSES TERKONTROL', 'Tidak semua pengguna perlu memiliki akses ke seluruh data dan tindakan transaksi.', 'Pisahkan akses berdasarkan role untuk mendukung kontrol operasional.', ['role dan permission', 'mendukung least privilege', 'akses tim lebih jelas', 'audit aktivitas lebih mudah ditinjau'], ['roles', 'users', 'workflow', 'reports'], ['aplikasi-bengkel-multi-user', 'aplikasi-bengkel-multi-cabang', 'source-code-aplikasi-bengkel']],
            'multi-cabang' => ['Aplikasi Bengkel Multi Cabang untuk Operasional Terpusat', 'Aplikasi Bengkel Multi Cabang untuk Jaringan Workshop', 'Kelola kebutuhan multi-cabang dengan struktur user, data, inventory, transaksi, dan laporan sesuai scope aplikasi.', 'MULTI CABANG', 'Jaringan workshop membutuhkan visibilitas terpusat tanpa mengabaikan batas cabang.', 'Bahas struktur cabang, akses, dan laporan yang dibutuhkan saat konsultasi implementasi.', ['mendukung struktur cabang', 'role dan akses pengguna', 'laporan operasional', 'scope deployment dapat dibahas'], ['multi_branch', 'roles', 'inventory', 'reports'], ['aplikasi-bengkel-role-management', 'aplikasi-bengkel-laporan', 'source-code-aplikasi-bengkel']],
            'laporan' => ['Aplikasi Bengkel dengan Laporan Usaha dan Operasional', 'Laporan Bengkel untuk Melihat Kinerja Operasional', 'Gunakan laporan service, penjualan, stock, teknisi, customer, dan keuangan yang tersedia untuk membantu evaluasi usaha.', 'DATA UNTUK KEPUTUSAN', 'Pemilik sulit mengevaluasi usaha jika data transaksi tidak dirangkum konsisten.', 'Satukan data operasional agar laporan dapat dipakai untuk membaca tren dan tindak lanjut.', ['laporan service dan sales', 'laporan stock', 'laporan teknisi dan customer', 'laporan keuangan sesuai modul'], ['reports', 'inventory', 'invoice', 'history'], ['aplikasi-bengkel-inventory', 'aplikasi-bengkel-multi-cabang', 'source-code-aplikasi-bengkel']],
            'booking' => ['Aplikasi Bengkel dengan Booking dan Walk-In', 'Booking dan Walk-In dalam Alur Aplikasi Bengkel', 'Terima customer dari booking online maupun walk-in lalu lanjutkan ke check-in dan proses service dalam satu alur.', 'CUSTOMER MASUK', 'Tim front desk perlu membedakan sumber kedatangan tanpa membuat data customer terpisah.', 'Gunakan booking dan walk-in sebagai pintu masuk menuju proses operasional yang sama.', ['booking online', 'walk-in service', 'check-in kendaraan', 'data customer tersambung'], ['booking', 'customers', 'vehicles', 'checkin'], ['aplikasi-bengkel', 'aplikasi-bengkel-mobil', 'source-code-aplikasi-bengkel']],
            'riwayat-servis' => ['Aplikasi Bengkel dengan Riwayat Servis Customer', 'Riwayat Servis Customer dan Kendaraan yang Mudah Ditelusuri', 'Simpan konteks kunjungan, temuan, pekerjaan, parts, invoice, dan status service agar tim memahami histori customer.', 'HISTORI SERVICE', 'Customer mengharapkan tim memahami kendaraan dan pekerjaan sebelumnya.', 'Hubungkan data kendaraan dengan histori service yang dapat ditinjau sesuai akses.', ['histori customer dan kendaraan', 'pekerjaan sebelumnya mudah dicari', 'mendukung rekomendasi berikutnya', 'data membantu layanan berulang'], ['history', 'customers', 'vehicles', 'work'], ['aplikasi-service-mobil', 'aplikasi-service-motor', 'source-code-aplikasi-bengkel']],
        ];

        foreach ($features as $slug => $definition) {
            [$title, $h1, $intro, $eyebrow, $problem, $solution, $benefits, $featureKeys, $related] = $definition;
            $pages['aplikasi-bengkel-'.$slug] = self::page('feature', $title, $h1, $intro, $eyebrow, $problem, $solution, $benefits, $featureKeys, 'Pemilik dan tim bengkel yang ingin memahami manfaat '.$h1.'.', $related);
        }

        $pages['aplikasi-bengkel-vs-excel'] = self::page('comparison', 'Aplikasi Bengkel vs Excel | Mana yang Lebih Terstruktur?', 'Aplikasi Bengkel vs Excel untuk Operasional Harian', 'Bandingkan pencatatan bengkel dengan spreadsheet berdasarkan alur customer, pekerjaan, inventory, dokumen, dan laporan.', 'PERBANDINGAN WORKFLOW', 'Excel berguna untuk mulai mencatat, tetapi koordinasi status dan relasi data lebih sulit saat transaksi bertambah.', 'Aplikasi khusus memberi struktur domain, role, status, dan dokumen yang sesuai operasional bengkel.', ['Excel fleksibel untuk catatan sederhana', 'aplikasi lebih kuat untuk workflow terhubung', 'role dan histori lebih mudah dikendalikan', 'pilihan bergantung pada skala dan kebutuhan'], ['workflow', 'inventory', 'roles', 'reports'], 'Pemilik bengkel yang membandingkan spreadsheet dengan software.', ['source-code-aplikasi-bengkel', 'harga-aplikasi-bengkel', 'aplikasi-bengkel-laporan']);
        $pages['software-bengkel-vs-excel'] = self::page('comparison', 'Software Bengkel vs Excel untuk Manajemen Workshop', 'Software Bengkel vs Excel: Fokus pada Alur Kerja', 'Lihat perbedaan software bengkel dan Excel dari cara mengelola customer, kendaraan, pekerjaan, stok, QC, invoice, dan laporan.', 'PILIH SISTEM KERJA', 'Spreadsheet tidak otomatis menyediakan status pekerjaan dan permission per peran.', 'Software bengkel dirancang untuk alur dan data yang saling terhubung.', ['workflow khusus bengkel', 'data customer dan kendaraan', 'inventory dan pekerjaan', 'laporan serta akses peran'], ['workflow', 'customers', 'inventory', 'roles', 'reports'], 'Pemilik dan manager workshop.', ['aplikasi-bengkel-vs-excel', 'source-code-aplikasi-bengkel', 'aplikasi-bengkel-multi-user']);
        $pages['alternatif-pencatatan-bengkel-manual'] = self::page('alternative', 'Alternatif Pencatatan Bengkel Manual | Gunakan Software Terstruktur', 'Alternatif Pencatatan Bengkel Manual', 'Jika buku atau spreadsheet mulai menyulitkan pencarian data, aplikasi bengkel dapat menjadi alternatif untuk menyusun customer, pekerjaan, parts, dan laporan.', 'ALTERNATIF SOFTWARE', 'Pencatatan manual tidak memberi status dan akses konsisten saat tim bertambah.', 'Mulai dari workflow digital yang paling penting lalu kembangkan sesuai kebutuhan.', ['workflow terpusat', 'histori mudah ditelusuri', 'estimasi dan dokumen lebih rapi', 'laporan operasional tersedia'], ['workflow', 'estimates', 'inventory', 'reports'], 'Bengkel yang mencari alternatif dari catatan manual.', ['aplikasi-bengkel-vs-excel', 'source-code-aplikasi-bengkel', 'harga-aplikasi-bengkel']);

        return $pages;
    }

    /** @return array<string, array{name: string, description: string}> */
    public static function features(): array
    {
        return [
            'booking' => ['name' => 'Booking & Walk-In', 'description' => 'Terima customer dari booking maupun walk-in lalu lanjutkan ke check-in.'],
            'customers' => ['name' => 'Data Customer', 'description' => 'Simpan identitas dan konteks customer untuk kunjungan berikutnya.'],
            'vehicles' => ['name' => 'Data Kendaraan', 'description' => 'Hubungkan customer dengan kendaraan, keluhan, dan histori service.'],
            'checkin' => ['name' => 'Check-In', 'description' => 'Catat kendaraan masuk, odometer, keluhan, dan kondisi awal.'],
            'findings' => ['name' => 'Temuan & Rekomendasi', 'description' => 'Dokumentasikan hasil pemeriksaan sebelum menentukan rencana pekerjaan.'],
            'estimates' => ['name' => 'Estimasi Customer', 'description' => 'Susun parts dan jasa sebagai informasi harga sebelum pekerjaan dilakukan.'],
            'approval' => ['name' => 'Approval Customer', 'description' => 'Dukung keputusan customer per scope sesuai arsitektur approval yang tersedia.'],
            'jobcards' => ['name' => 'Job Card', 'description' => 'Berikan konteks dan tugas pekerjaan kepada mekanik.'],
            'work' => ['name' => 'Pekerjaan Mekanik', 'description' => 'Pantau pekerjaan dan status operasional sampai siap QC.'],
            'parts' => ['name' => 'Sparepart', 'description' => 'Gunakan parts dalam estimasi dan pekerjaan dengan data product terstruktur.'],
            'inventory' => ['name' => 'Inventory', 'description' => 'Kelola product, stock, movement, pembelian, dan pemakaian parts.'],
            'qc' => ['name' => 'Quality Control', 'description' => 'Periksa hasil pekerjaan sebelum kendaraan diselesaikan.'],
            'invoice' => ['name' => 'Invoice', 'description' => 'Buat invoice dari pekerjaan dan scope komersial yang sudah diproses.'],
            'payments' => ['name' => 'Pembayaran', 'description' => 'Kelola pembayaran pada domain invoice yang terpisah dari estimate.'],
            'history' => ['name' => 'Riwayat Service', 'description' => 'Telusuri kunjungan, pekerjaan, parts, dan dokumen kendaraan.'],
            'reports' => ['name' => 'Laporan Usaha', 'description' => 'Gunakan laporan service, sales, stock, customer, teknisi, dan keuangan.'],
            'users' => ['name' => 'Multi User', 'description' => 'Dukung kerja bersama front desk, mekanik, QC, kasir, dan pemilik.'],
            'roles' => ['name' => 'Role Management', 'description' => 'Atur akses pengguna berdasarkan tanggung jawab.'],
            'multi_branch' => ['name' => 'Multi Cabang', 'description' => 'Bahas struktur cabang, akses, inventory, dan laporan untuk jaringan workshop.'],
            'whatsapp' => ['name' => 'WhatsApp Customer', 'description' => 'Kirim ringkasan estimasi dan tautan publik melalui WhatsApp.'],
            'workflow' => ['name' => 'Workflow Bengkel', 'description' => 'Jaga alur dari customer masuk sampai kendaraan selesai tetap terstruktur.'],
            'source_code' => ['name' => 'Full Source Code', 'description' => 'Source code disediakan sesuai paket dan lisensi yang disepakati.'],
            'customization' => ['name' => 'Customisasi', 'description' => 'Bahas perubahan workflow, branding, dan integrasi sesuai kebutuhan.'],
            'deployment' => ['name' => 'Web Deployment', 'description' => 'Konsultasikan server, domain, dan deployment berdasarkan kebutuhan implementasi.'],
            'integration' => ['name' => 'Integrasi', 'description' => 'Petakan kebutuhan integrasi tambahan dalam scope teknis yang jelas.'],
        ];
    }

    /** @return array<string, mixed> */
    private static function page(string $intent, string $title, string $h1, string $intro, string $eyebrow, string $problem, string $solution, array $benefits, array $featureKeys, string $audience, array $related): array
    {
        return compact('intent', 'title', 'h1', 'intro', 'eyebrow', 'problem', 'solution', 'benefits', 'featureKeys', 'audience', 'related');
    }
}
